### ISSUE TITLE
Dark line under stackswitcher does not work on first/last child

### ISSUE THREAD

**Issue by clobrano** [Ubuntu/gtk-communitheme#106]
![image](https://user-images.githubusercontent.com/2883614/35405200-b79481fa-0205-11e8-8a02-82f8fa5eda9d.png)

This is a problem I introduced in my implementation of new the breadcrumb. I didn't considered that first/last child are not only the arrows in breadcrumb

**Comment by godlyranchdressing** [comment]
.slider-button should be the class for the arrows on the left and right, I think. Is $silk being used because $headerbar_insensitive_color doesn't look disabled enough?

The SCSS for the stackswitcher and path-bar needs to be cleaned up, but we should probably put that on hold till after we decide on a final look anyway. 

For the current design, the black rail doesn't show up well on my laptop, maybe we can use $slate?

**Comment by clobrano** [comment]
> Is $silk being used because $headerbar_insensitive_color doesn't look disabled enough?

$silk is used when the arrows in path-bar are enabled, but not hover and I was having hard time to differentiate disabled/enabled/hover just with colors so +1 for keeping this on hold until we have a clear direction 👍

**Comment by clobrano** [comment]
> For the current design, the black rail doesn't show up well on my laptop, maybe we can use $slate?

I'll propose it on the forum
