### ISSUE TITLE
Some applications still doesn't respect headerbar title size

### ISSUE THREAD

**Issue by madsrh** [ubuntu/gtk-communitheme#116]
Firefox, Thunderbird, Xchat and A Widget Factory still doesn't respect headerbar title size.

![title-size](https://user-images.githubusercontent.com/3986894/35486777-2ef70942-0473-11e8-972e-59ad135c4516.jpg)

**Comment by godlyranchdressing** [comment]
I know Firefox and AWF use regular titlebars (.default-decoration), but most GTK3 apps use headerbars. They both have different dimensions in use but if we make them uniform then we'll end up with headerbars being too small or titlebars being too large. It's something we'll have to live with, unfortunately.

**Comment by clobrano** [comment]
So can we close this?

**Comment by ya-d** [comment]
To my understanding the issue was with respecting the *font size and style* set by your gtk theme, wasn't it? Apps using title bars can/must be be configured via Tweaks > Fonts > Window Title, while GTK3 apps get their size from Tweaks > Fonts > Interface with font style set by the theme. So this issue is rather the other way round, gtk3 apps don't respect the system wide setting for Window Titles (as they aren't window titles but header bar titles within the apps interface).

From a users point of view ideally all gtk2 or gtk3 apps would use the user configurable setting for "Window Title" font but that is probably out of reach for this theme. (Or can this value be accessed in css?) But in my opinion both should be consistent at least for standard settings.

Adwaita behaves the same but uses bold style for titles in header bars. Right now Communitheme uses a regular style font for titles in header bars which makes them indistinguishable from other text (buttons), see #127.

// by the way
I though using medium weight would be an option if you consider bold to be to heavy, but both medium and bold fonts seem to be rendered the same weight for me. Same for you? Maybe only "standard styles" like regular, italic, bold, bold italic are properly supported.

**Comment by clobrano** [comment]
> To my understanding the issue was with respecting the font size and style set by your gtk theme, wasn't it? 

I thought it was about the height itself, but as @godlyranchdressing said, titlebars and headerbars are inherently different and or the titlebar looks too big (consider also the space occupied by menubar below) or the headerbar is too small (and contained buttons/entries... will be affected).
 
If I'm wrong, let's keep it open and maybe we can change the title. If there's inconsistency between titlebar and headerbars' fonts better open a new ticket. What do you think?

**Comment by ya-d** [comment]
I read it like "headerbar title (font) size" not "headerbar / title(bar) size". Up to @madsrh to clear up and decide. I'm good with #127 which seems to be already addressed in #138. ;-)

**Comment by madsrh** [comment]
Perhaps I'm using the wrong term here. What I mean is the text in the image above "A widget factory" should be 9px like "Appearance", "Ubuntu Desktop Guide" and the terminal.

**Comment by ya-d** [comment]
Yeah, you can change that with live visual feedback in Tweaks > Fonts > Window Title. Maybe it is possible that the GTK theme parses those values as well for headerbar titles, fixing this issue the other way round and make all title styles consistent and customizable within Gnome Tweaks as a bonus.

**Comment by clobrano** [comment]
Sorry then, my mistake. Thanks for stopping me closing this :D

**Comment by clobrano** [comment]
This looks fixed now

**Comment by nana-4** [comment]
As far as I know, it is impossible to parse the values in the GTK theme and apply them to the headerbar titles.

Since this is not the theme issue, I think this can be closed.
