### ISSUE TITLE
Deactivated switches and switches in off state looks the same

### ISSUE THREAD

**Issue by madsrh** [Ubuntu/gtk-communitheme#119]
At a glance, deactivated switches and switches in off state looks almost the same. Adding a bit of gray to the white knob itself, would emphasize that this is deactivated. If possible I would use the same gray as the background (of the switch) at 50% opacity.

**Comment by clobrano** [comment]
This is with 50% opacity
![image](https://user-images.githubusercontent.com/2883614/35586107-313278f8-05fa-11e8-9060-657cce7285e6.png)

I also tried transparent by 20%, what do you think?
![image](https://user-images.githubusercontent.com/2883614/35586060-0567c340-05fa-11e8-9d94-1b34d53f78fc.png)

**Comment by madsrh** [comment]
@clobrano Ahhh, I see what you did there :) I meant 50% of the deactivated gray (#e4e4e4) which then becomes something like #f0f0f0. But you 20% one you posted looks good

**Comment by didrocks** [comment]
I prefer the 20% transparency: they look more like the same buttons in different state. I don't know why, but with the 50% case, I feel like it's 2 different items, not the same.

**Comment by clobrano** [comment]
@madsrh sorry, I misunderstood :D. Let me try with #F0F0F0, then I'll do the PR

**Comment by clobrano** [comment]
Here is #F0F0F0

![image](https://user-images.githubusercontent.com/2883614/35632394-d6f50092-06a6-11e8-8bbf-94c518bd747b.png)

I think I'll go with 20% transparency, though

**Comment by ya-d** [comment]
Also consider colors for inactive windows, please. Top switch is off, bottom is on. Makes no sense to me that they use different colors, especially for the 'knobs'. IMHO the grey for off-state should be the same brightness as the green for on. So that a desaturated on-switch in an inactive window is of the exact same grey than an off-switch.

<img width="105" alt="switches_inacitve-windows" src="https://user-images.githubusercontent.com/30781876/35632699-9ebf0c62-06a7-11e8-9190-f7e3a6fc5491.png">

**Comment by galgalesh** [comment]
What's also an option is to give disabled elements the same colors as the background. That is strong signalling to the user: backgrounds are not clickable, so everything that looks like a background is unclickable. An example in ambiance; enabled vs disabled listbox

![image](https://user-images.githubusercontent.com/1492981/35633881-a5aa63c0-06aa-11e8-9675-e0a19719356b.png)

(also; make all elements flat when disabled, this is a very common design pattern; but I think we're already doing that)

**Comment by clobrano** [comment]
> Makes no sense to me that they use different colors, especially for the 'knobs'. 

I agree about the knobs

> So that a desaturated on-switch in an inactive window is of the exact same grey than an off-switch.
Do not agree. I think it's important that widgets with different states keep the difference in an inactive window

**Comment by madsrh** [comment]
I like the one at 20%. I fully agree with both ya-d and Merlijn. I'm not sure how well the background-less switch will work here though. [Like these](https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/0680a89167057.58dd31a720caf.png)? @clobrano can you post a screenshot with a transparent background?

@ya-d Good points! I could try a few color combinations and post the result here.

We already discussed this, but the "colored-knobs switches", I suggested earlier might also be better for usability. [Here](https://ubuntucommunity.s3-us-east-2.amazonaws.com/original/2X/e/e1d3a755ab485236395a2fc987e8b739a6f6b7f1.jpg) with icons

![7f5af1b5851e47e12029833fb90d470d8a83c66e_1_690x383](https://user-images.githubusercontent.com/3986894/35648086-d23064f6-06d4-11e8-8fb9-448c573548fd.gif)

**Comment by clobrano** [comment]
> @clobrano can you post a screenshot with a transparent background?

It would roughly be this way. We can play a little more with borders' color, but I'm not convinced with the result, too evanecent to me

![image](https://user-images.githubusercontent.com/2883614/35649252-c88f2b2c-06d8-11e8-88f4-4a3a24e6fe58.png)

**Comment by madsrh** [comment]
I think that looks good for switches in backdrop @clobrano : 

![toggles_](https://user-images.githubusercontent.com/3986894/35652137-a9d6d572-06e2-11e8-82c1-391e220fab75.jpg)

Could we use that for deactivated switches in active windows also or would that be confusing?

![toggles_2](https://user-images.githubusercontent.com/3986894/35652651-d109e506-06e4-11e8-8337-cf4f4a369f1e.jpg)

**Comment by galgalesh** [comment]
I like the transparent background switches, especially for an unfocused window, but I think it needs some tweaking.

What about having the background transparent but making the knob/button itself grey? I like this conceptually because this way, the background of the switch signals its "state":

 - colored = enabled and on
 - grey = enabled and off
 - transparent = disabled

Another thing you could try is to only make the knob/button transparent and make the background 20% or something. This is also nice conceptually because the thing that you can change, i.e. the button itself is the same color as the background, because the button is disabled. The switch itself is still there, and has a position, you just can't change it because the button of the switch doesn't work.

**Comment by galgalesh** [comment]
Also, what are the Canonical design guidelines for the switch? How did they solve the issue?

**Comment by madsrh** [comment]
Good point, we should try that.

Canonical does this a bit different. They are using their switches [on a white window background](https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/0680a89167057.58dd31a720caf.png) - here the deactivated background of the switch are a light gray (almost same color as our window background): https://github.com/CanonicalLtd/desktop-design/blob/master/Switch/Switch.png

**Comment by clobrano** [comment]
@madsrh 

> I think that looks good for switches in backdrop

But then how can we keep the difference between checked and unchecked switches in backdrop?
If we get rid of any color, all switches will look the same. As example, the picture below, are they both disabled or one is disabled and one just unchecked?

![image](https://user-images.githubusercontent.com/2883614/35690083-43136736-0775-11e8-913e-4218692d5616.png)


> Could we use that for deactivated switches in active windows also or would that be confusing?

Do you suggest to use transparent for both unchecked and deactivated/disabled switches? That would be confusing, I think

@galgalesh 

> What about having the background transparent but making the knob/button itself grey?

There was a proposal from @madsh very similar. At some point we decided for colored backround and knob white, since I think that let us use more colors to distinguish different states


> Also, what are the Canonical design guidelines for the switch? How did they solve the issue?

The picture misses the backdrop variation of those states (and I really don't like Unity8, sorry :D)

**Comment by Luxamman** [comment]
I also would see the deactivated with a border only, but the not in focus (not deactivated) with a slight grey.

**Comment by galgalesh** [comment]
@clobrano the difference between checked and unchecked deactivated buttons is the position of the knob of the button. In your example, both buttons are unchecked.

**Comment by clobrano** [comment]
> In your example, both buttons are unchecked.
I thought that at least one was unchecked and disabled

**Comment by clobrano** [comment]
So, this is the current state before @Luxamman request

![transparent-switcher](https://user-images.githubusercontent.com/2883614/35868466-df129c34-0b5c-11e8-8b3b-2ba1e7a226f4.gif)

as I said before, backdrop:unchecked and disabled look the same

@Luxamman by "not in focus" do you mean the checked ones when the windows is not on focus (backdrop)? If that so, I tried some combination, but the light gray tends to merge with the border color, so that the switcher looks too different respect the others (disabled and unchecked).

**Comment by galgalesh** [comment]
I feel as if there is some miscommunication here so excuse me if I'm repeating stuff that's already said.

A disabled button can be either disabled+checked or disabled+unchecked. The difference between these is in the position of the "knob" of the button: left = unchecked, right = checked.

The current discussion is about the difference between focused/backdrop right?

**Comment by clobrano** [comment]
@galgalesh no worries, surely it's better to clear any misunderstanding 😉 

You're right, the position of the knob is perfect for checked/unchecked switches in backdrop state. 

What I am worried now is that, when in a backdrop state, there is no difference between an unchecked switch and a unchecked-and-disabled one because they are both totally transparent.
In the picture below, the upper switch is just unchecked, the bottom one is disabled

![image](https://user-images.githubusercontent.com/2883614/35870116-18146f40-0b61-11e8-866e-7bca7759abc3.png)
