### ISSUE TITLE
Style application dialogs to match interactive dialogs

### ISSUE THREAD

**Issue by madsrh** [Ubuntu/gtk-communitheme#130]
It seems inconsistent with three different kinds of dialogs. Especially the white dialog with rounded corners _(that nothing else in the UI has)_ jumps in my eye. 

Could we change the white dialog design to match the dark look of system menu, calendar, brightness, ...?

![dialogs](https://user-images.githubusercontent.com/3986894/35614539-b759b5d4-066f-11e8-84a2-599574366dbc.gif)

**Comment by clobrano** [comment]
It's weird, but the two dialogs show above from gtk (close terminal one and confirm close) are actually two different things. The first is a message dialog/box, the latter an interactive dialog. Not sure about why this distinction, but I think we should keep it, so that I styled only the first in my PR, since the latter already shows a "communitheme valid" style.
Just my opinion though, so let me know your feedback

**Comment by madsrh** [comment]
@clobrano Sorry, yes that was a bit unclear from my post. The gif was merely to emphasize that three different styles are used. But YES the GTK (Firefox) shouldn't change, only the "white dialogs" should match the dark look. Apologizes for the confusion.

**Comment by clobrano** [comment]
@madsrh no worries, I didn't even recognize the dialog came from Firefox 😂.
I used gtk3-demo>dialog-and-message-boxes demo and there are two different demos there, so it would make sense style them similarly, but since one of the two (the interactive one) is already styled, I thought it wasn't necessary to do it differently.

**Comment by galgalesh** [comment]
Closing this issue since we think it's better to keep the difference between the application message dialog and the shell dialog. It will help users figure out what is happening. To quote @didrocks:

> I think that having them differentiated actually help: "is it something from the system or is it something specific to the app?". (without talking about security, just user's hint here).

Feel free to reopen it if you think it needs more discussion.

**Comment by madsrh** [comment]
https://community.ubuntu.com/t/mockups-new-design-discussions/1898/263

Can I reopen this issue for "add blank headerbar and less rounded corners on application dialogs"? _(I forgot  to change the roundness in the mockup)_

![headerbar](https://user-images.githubusercontent.com/3986894/36585887-ec918a98-187f-11e8-8302-04ed65a3fa8e.jpg)

**Comment by galgalesh** [comment]
Why not also change the buttons into our regular  buttons?

**Comment by clobrano** [comment]
That would make it the same as another type of dialog window. So if we decide to do it, they have to be exactly the same, but at this point, as @didrocks said, we won't know which dialog is anymore

**Comment by madsrh** [comment]
@galgalesh Yes, that would make sense to me.
@clobrano Well this one has an empty headerbar. Aren't they both application dialogs? As I understood @didrocks comment, the issue was only to distinguish application dialogs from shell dialogs.

**Comment by galgalesh** [comment]
Yes, they are both application dialogs, the dark ones are different, those should stay the same, but this proposal is only for the light ones, right?

**Comment by madsrh** [comment]
@galgalesh right!

**Comment by clobrano** [comment]
What about this?

![image](https://user-images.githubusercontent.com/2883614/36633294-111fda22-1993-11e8-8fe6-29bb0f657ee1.png)

I'm still investigating whether this kind of window dialog forced the button to stay centered in their positions or not

**Comment by madsrh** [comment]
Yes @clobrano! 👍This, to me, feels much more as part of the theme.

**Comment by clobrano** [comment]
It seems I made a too big deal about differences between interactive and message dialogs, sorry!
Looking at the code in gtk3-demo, it looks that interactive dialogs are just a lot more manually styled, while message dialogs are a simpler way to do dialogs.
So, I'm going to propose this change as it is.

**Comment by didrocks** [comment]
:+1: Thanks for getting us back on track @madsrh ;) (Yes, I'm backlogging your current crazy 355 github messages while I was away :p)

**Comment by madsrh** [comment]
> @didrocks Yes, I'm backlogging your current crazy 355 github messages while I was away :p)

Only surpassed by @clobrano is at 356 :stuck_out_tongue_winking_eye: ...and welcome back!

**Comment by galgalesh** [comment]
I just saw my first newly styled dialog, and I really like it! Good job!

**Comment by pojntfx** [comment]
I'm not so sure about the new design but since the community has voted for it, it should definitely be accepted.
![screenshot from 2018-03-06 21-57-27](https://user-images.githubusercontent.com/28832235/37058185-fd473b7c-2189-11e8-9411-3d7e02106c48.png)
Looking at dialogs closely however something seems to be off to me. Would it be possible to make the margin/padding beneath the buttons a bit bigger? Since the margin on the side seem to be bigger this looks a bit weird to me (tested this with gedit) ;).

**Comment by madsrh** [comment]
Well spotted @pojntfx +1

**Comment by clobrano** [comment]
> Would it be possible to make the margin/padding beneath the buttons a bit bigger?

very possible :wink:
