### ISSUE TITLE
Check marks in list box should probably be green

### ISSUE THREAD

**Issue by ya-d** [ubuntu/gtk-communitheme#135]
…as they indicate an active selection similar to radio or check buttons. See Tweaks > Windows for example.

<img width="921" alt="selection-arrow_green" src="https://user-images.githubusercontent.com/30781876/35634743-b65a2820-06ac-11e8-8892-a037ed5ab338.png">

**Comment by clobrano** [comment]
I think this comes directly from Adwaita, where check marks are black in check buttons as well, while in Communitheme they are white with green background. I wonder if they would be less visible if green, though, since is a lighter color

**Comment by madsrh** [comment]
Yes, checkmarks should green! Following the [guide by Canonical](https://github.com/CanonicalLtd/desktop-design/tree/master/Check%20boxes%20and%20radio%20buttons).

![image](https://user-images.githubusercontent.com/3986894/36026793-ea9fa4be-0d98-11e8-8d4a-baa987fbf77e.png)

**Comment by clobrano** [comment]
Does anybody knows from where this tick comes from? It's not the one under gtk-3.0/assets

**Comment by godlyranchdressing** [comment]
I'm not sure where the icon is from. Maybe a fallback icon from the Adwaita theme? It's present in GNOME Software as well. 

Either way, the checkmark in GNOME Tweaks isn't a "real checkbox" like the others that use the green, hence the different icon and black color. I feel bad for saying it since I have no clue how to contribute to GNOME Tweaks, but I don't think it was implemented well. Maybe it should be reported as a bug?

It can be fixed, but I don't know if we should bother:
`#ListBoxTweakGroup #Focus box ~ image { color: $success_color } `

**Comment by didrocks** [comment]
I just summoned Jeremy Bicha, GNOME Tweaks upstream, pointing him to this thread so that you can discuss the issue :)

**Comment by jbicha** [comment]
It is [`object-select-symbolic`](https://gitlab.gnome.org/GNOME/gnome-tweaks/blob/master/gtweak/tweaks/tweak_group_windows.py#L45). I believe you'll find it's also used in `gnome-control-center` and several other GNOME apps.

**Comment by nana-4** [comment]
In the GTK-CSS, these check marks are just `image`, not `check`, and usually don't have a specific style class. Therefore, we cannot change the color of all check marks exactly. So I think this can be closed as `wont fix`.

**Comment by clobrano** [comment]
Thank you @nana-4 
closing this
