### ISSUE TITLE
Add separation line between windows and top-bar

### ISSUE THREAD

**Issue by Luxamman** [ubuntu/gtk-communitheme#154]
Separation line between windows and top-bar are not present when windows are touching. They appear when maximizing the window.

**Comment by clobrano** [comment]
As far as I know (which is an alias for @godlyranchdressing please correct me, if I'm wrong 😄), the window doesn't know if it's only touching the top-bar, since none of the .maximized, .tiled, etc. style classes are applied.
If we want this feature, the only way is to move it into gnome-shell-communitheme, but in this case the top-bar will have a separation every time it gets opaque, that is even when no window is maximized, nor touching it (the transition to opaque starts when any window is "closer enough" to top-bar or dock)

**Comment by godlyranchdressing** [comment]
@clobrano is right. The most that can be done is letting the top bar get a separator when a window is "close enough".

**Comment by clobrano** [comment]
separation line is present now, closing this
