### ISSUE TITLE
Bread crumbs and StackSwitcher: rounded corners, vertical separators and consistency

### ISSUE THREAD

**Issue by ya-d** [Ubuntu/gtk-communitheme#160]
1. Both elements should use rounded corners as do regular buttons. (Arrows in bread crumbs use an even larger radius, while StackSwitcher is not rounded at all.)
2. Bread crumbs and some StackSwitcher elements like in Widget Factory or Rythmbox use vertically separating lines between connected buttons, while others do not (Software). Looked much cleaner without separators to me. In any case: stay consistent! (They even are of different width in bread crumbs and StackSwitcher.)
3. Active selection uses bold font in bread crumbs but regular in StackSwitcher. I prefer bold. (See #127 #138 )

Also see #155 .

**Comment by madsrh** [comment]
1. The discussion for the breadcrumbs / stackswitcher buttons is [found here](https://community.ubuntu.com/t/mockups-new-design-discussions/1898/244).

2. Can we try changing the separator color to #383535 like the slider-button background? I agree that the current design looks less clean.

3. I can't find any reference to text color in Stefan's post, but we should change the selected button text to white (currently #cecece) and IMHO **NOT** bold. I would argue that an orange line and white text makes it pretty easy to spot where you are. Also the bold font doesn't render that well.

**Comment by nana-4** [comment]
I wonder if breadcrumbs / stackswitcher really should have a brighter background.

Because **stackswitcher** has underline marks but does **not** have arrows, [it's hard to round the corners technically](https://user-images.githubusercontent.com/9556384/36337218-e6327022-13d4-11e8-8b2e-65d0175cca86.png). (Even with the original mockup, stackswitcher corners are not rounded, though.)

Or we can round [only the upper corners](https://user-images.githubusercontent.com/9556384/36336944-7e9eb3b6-13d0-11e8-9dd5-ab6b0311d99a.png), but it may seem odd.

Or I think it's also okay to remove the background only from stackswitcher, as #168 has already done.

**Comment by nana-4** [comment]
Sorry, but I take back my previous comment because I came up with a way to round stackswitcher well.
I will send the PR.

**Comment by ya-d** [comment]
Cool! 🎉 Thanks for the effort!

I'm probably the only one who would like active stack to be bold?! I suggest weight 500 for this as well as for path bar (seems a bit heavier at the moment), compare #171.

**Comment by nana-4** [comment]
@ya-d IMHO I'd prefer normal weight for the selected buttons. It's because more Suru-ish. (See also #181) But in any case, **stackswitcher**, **pathbar** and **tabs** should have consistent font weights and text colors IMHO.

About the Nautilus pathbar; Unfortunately, the font weight of the selected button in pathbar is hard-coded to **bold** with upstream Nautilus so we cannot change the weight by the theme. So I think we should consider the weight of the Nautilus pathbar as an exception.

**Comment by ya-d** [comment]
Thanks for the pointer, don't know of these practical limitations. Always +1 for consistency. 😄

**Comment by clobrano** [comment]
What about this?
![image](https://user-images.githubusercontent.com/2883614/36633279-cf0125ce-1992-11e8-9835-7fcb1ba01e1d.png)

I'm still investigating if this kind of window dialog forces the buttons to occupy the most of the space.

**Comment by ya-d** [comment]
Closed by #168 and #180. Thanks! 🎉
