### ISSUE TITLE
Update check boxes/radio buttons to match design intended by Canonical

### ISSUE THREAD

**Issue by ya-d** [ubuntu/gtk-communitheme#162]
Disabled check boxes/radio buttons should probably stay grey, while with the latest update they became green. (No choice means no "positive" selection.) Maybe use the lighter green for partially selected instead. (I personally prefer ditching yellow for mixed sate.)

<img width="323" alt="check boxes" src="https://user-images.githubusercontent.com/30781876/36152653-fdf7cb5a-10cb-11e8-9399-8d90d5d9e47e.png">

**Comment by madsrh** [comment]
Shouldn't we apply the Canonical design here too? The second row with the gray checkbox looks disabled to me (and not just unchecked), but @godlyranchdressing might have a reason to differ from the design below - if not, I think we should try this:

![image](https://user-images.githubusercontent.com/3986894/36200742-eebd379e-117d-11e8-8ed8-a2ca2d34d367.png)

**Comment by galgalesh** [comment]
+1 for canonical design, it looks really slick.

**Comment by clobrano** [comment]
I was also thinking about this

> No choice means no "positive" selection.

Maybe it's possible to have something checked, but that you cannot uncheck, so +1 also for me

**Comment by clobrano** [comment]
I think I can close this

**Comment by madsrh** [comment]
@clobrano  is there a PR for this? I don't see any commit in this issue?

**Comment by clobrano** [comment]
Maybe I misunderstood, but wasn't the bug request to change what is already implemented?

**Comment by madsrh** [comment]
Sorry, It's me (again). I understand that this issue was refering to row number four above (the disabled checkbox/radio that can't be unchecked). 
I figured that since there's a +1 for following the Canonical design, we should implement that, not just for the  disabled checkbox/radio that can't be unchecked, but also for the normal checkbox/radio (second row in #1 comment and first row in the image below).

![checkandradio](https://user-images.githubusercontent.com/3986894/36283771-c597031c-12a5-11e8-86dd-988cf38746cf.jpg)

@clobrano should I create a separate issue for this?

**Comment by clobrano** [comment]
@madsrh I feel stupid, but I don't understand 😄 , so sorry if I keep asking clarifications

Second row in first comment is
![image](https://user-images.githubusercontent.com/2883614/36298084-8f3e9b58-12f6-11e8-865f-0c43be43519d.png)

First row in the picture you posted is
![image](https://user-images.githubusercontent.com/2883614/36298119-bbcd1b22-12f6-11e8-87cf-e91e70307f22.png)

So, If I understood correctly this time, the first one should be made, let's say, lighter and more transparent, but the second one looks good. Did I misunderstand again? 😨

**Comment by madsrh** [comment]
I'm the one spreding confusion, so don't be sorry ;)

Yes, we want **this**: 
![image](https://user-images.githubusercontent.com/3986894/36298872-9594345a-12fa-11e8-9d93-a4a0f1efc851.png)

I guess it should have the same properties as this box: light background, gray border.
![ikke-navngivet-1](https://user-images.githubusercontent.com/3986894/36299066-91825daa-12fb-11e8-93e9-002fc5903333.jpg)

Because in this one they look disabled, right?
![image](https://user-images.githubusercontent.com/3986894/36298893-b6839d86-12fa-11e8-9187-c2018cd09a2f.png)

**Comment by ya-d** [comment]
* Maybe try the checked but disabled state from Canonical as well? => more muted green with white check mark/point.
* For disabled state, colors should maybe blend with the background like the inactive "+/– box" (see 3 posts above) than?  => "transparent" background for square/circle (plus maybe adjusted grey tones for border and text to match those of the box)

Thank you very much, and sorry that I'm not able to provide some quick mockups, which would be much easier to understand than words…

**Comment by madsrh** [comment]
+1 from me.
@clobrano can you imitate the Canonical design for these?
It looks like they've just lowered the opacity but same colors.

**Comment by clobrano** [comment]
What about this?
![checkbox radiobox](https://user-images.githubusercontent.com/2883614/36318923-88f1de68-1341-11e8-93ba-55d01c8c444e.gif)

**Comment by ya-d** [comment]
Looks very good, I like the white background much better than the grey before. Would you mind trying my to suggestions? (White marks for inactive and selected, no background for inactive and non-selected.) But I'm happy as it is.

**Comment by madsrh** [comment]
Perfekt! Much better 👍

**Comment by clobrano** [comment]
> Would you mind trying my to suggestions? (White marks for inactive and selected

Tried with the same css used for normal selected, but the color didn't changed.

> no background for inactive and non-selected.
This is done already for backdrop

**Comment by madsrh** [comment]
A very tiny tweak here, but I'm reopening this because the green background in the disabled checkboxes/radios is currently the same color (only the white checkmark inside changes). See the Canonical design in comment #2 of this issue.

This is what we've got:
![image](https://user-images.githubusercontent.com/3986894/38707199-a990b154-3eb0-11e8-878f-538ecf7c76ab.png)


...and this is what we want:

![image](https://user-images.githubusercontent.com/3986894/38707191-a1ec06a6-3eb0-11e8-927d-200152a770d9.png)

**Comment by Feichtmeier** [comment]
@madsrh Is this fixed?

**Comment by madsrh** [comment]
Except for bug #367 yes :)

**Comment by clobrano** [comment]
#367 is addressed by PR #384
