### ISSUE TITLE
Remove space between headerbar and playqueue in Rythmbox

### ISSUE THREAD

**Issue by madsrh** [Ubuntu/gtk-communitheme#186]
Remove space between headerbar and playqueue / GtkNotebook in Rythmbox:

![screenshot](https://user-images.githubusercontent.com/3986894/36490370-674b3436-1728-11e8-84af-309d6c7b08f3.jpg)

**Comment by clobrano** [comment]
Good you spotted it @madsrh!
This is a side effect of #109 
Unfortunately, while in Nautilus there is a class name that let us remove the space when not needed, Rhythmbox does not. Moreover, Rhythmbox case is probably the most common, so the best solution would be to revert fix for #109

**Comment by nana-4** [comment]
This actually can be fixed by adding an additional Nautilus specific style class (`.nautilus-window`).

```
.nautilus-window {

  notebook > stack grid:not(.nautilus-list-view) {
    padding-top: 15px;
  }
}
```

BUT +1 for reverting #109 because the space looks odd even Nautilus when keeping to scroll upwards:

![image](https://user-images.githubusercontent.com/9556384/36497564-ff96707e-177e-11e8-91a9-90cb82fb3e52.png)

**Comment by NusiNusi** [comment]
Same space can be found in texteditor
![bildschirmfoto von 2018-02-22 18-43-56](https://user-images.githubusercontent.com/36449926/36554924-e41a47f8-1800-11e8-963c-9c4b44227000.png)

**Comment by clobrano** [comment]
nice catch!

**Comment by clobrano** [comment]
I'm going to prepare a PR with the fix suggested by @nana-4, so that we'll be ready for any decision
