### ISSUE TITLE
Inconsistency of mouse-over on inactive windows

### ISSUE THREAD

**Issue by CDrummond** [ubuntu/gtk-communitheme#194]
Most widgets with communitheme do not react to mouse over events in inactive windows. However some widgets still react/change appearance when the mouse hovers over them in inactive windows - e.g. tabs, 'link button' (URL style label), scrollbars, nautilus pathbar, and the page selector button in gtk3-widget-factory (sorry, don't know the widget's name - but the one in the middle of the header bar that is used to change pages).

IMHO, **all** widgets should still react to mouse-over in inactive windows - as they still accept button press events. e.g. press one of the 'togglebutton' widgets in gtk3-widget-factory in an inactive window - the window is raised, and the button is toggled, therefore the widget is active.

**Comment by ya-d** [comment]
Also discussed in #150.

**Comment by CDrummond** [comment]
Yes/no - this report mentions other widgets that still react when in inactive windows.

But, as stated, I agree that **all** widgets in inactive windows should react - as they still accept the mouse click. If the click simply raised the window, and the widget did not respond - then the current behaviour would be fine. But they do react, when they look like they would not - which is bad. Stating that this is the way Adwaita works, does not mean that it is a good idea.

**Comment by ya-d** [comment]
[I'm totally with you](https://github.com/Ubuntu/gtk-communitheme/pull/166#issuecomment-367441512), just wanted to provide the context to ease management and discussion.

**Comment by clobrano** [comment]
@Luxamman, @madsrh

**Comment by Luxamman** [comment]
The passive windows are tricky, I had to rethink them a little because the separation between active and passive windows is very harsh. 

This is especially irritation when working with two windows side by side (something very common I think) - because passive windows look almost like deactivated or like they hung up.

Like in other systems, it is good to give a hint which window is passive (like windows control orange getting grey and headerbar little lighter, and content colors getting brighter or grey), but maybe we should not separate the whole content and buttons too hard. 

When windows are stacked, they have separation lines and a shadow to be visually separated - so I'm with you to reduce the overall passive look - including buttons and content.

**Comment by mivoligo** [comment]
I'm probably going to repeat what was already mentioned: if the buttons of a background window does not react on hover, I would not expect them to work when clicked. Rather the click will get the window to the foreground.

**Comment by madsrh** [comment]
@CDrummond moving the discussion back here 😉 

I though I mentioned this in #212, but amt I can't find it. Anyway, my idea was that everything should behave **exactly** the same in backdrop - only darker. A "simple" color overlay to give the illusion that the window is further away or that the "spot light" is on the active window. Does this make sense?

![image](https://user-images.githubusercontent.com/3986894/39662797-acb4b97a-5067-11e8-883a-9847886859d1.png)

**Comment by CDrummond** [comment]
Yup - that makes perfect sense to me.

**Comment by clobrano** [comment]
Short update: I'll start working on this as soon @Feichtmeier's work on dark variant ends
