### ISSUE TITLE
The current button design doesn't work well with linked buttons

### ISSUE THREAD

**Issue by CDrummond** [ubuntu/gtk-communitheme#278]
Another **very** minor niggle. The shadows under buttons look great, but with split buttons the shadow does not extend between the buttons. It looks as if the shadow is per button. Screenshot is an `xmag` capture from `gtk3-widget-factory`

As stated, very minor niggle - feel free to ignore.

![screenshot from 2018-03-23 07-52-43](https://user-images.githubusercontent.com/1141694/37817608-4269f54a-2e6f-11e8-8666-f381971ab578.png)

p.s. Sorry for reporting such minor issues - just this is shaping up to be the best theme I've ever seen :-)

**Comment by clobrano** [comment]
> Sorry for reporting such minor issues

this is actually welcome, no worries :wink: 

I've seen this issue while developing the change, but couldn't find a solution, so I made it public so more people could look at it

**Comment by godlyranchdressing** [comment]
This might be a pain to fix. 

![linke](https://user-images.githubusercontent.com/27529229/37851041-ccf2de4a-2eb3-11e8-9852-49bf38ad4f1e.jpg)

The only button in that group of linked buttons that has a border-right is the very last button. Hovering them reveals that.

![hovering](https://user-images.githubusercontent.com/27529229/37851207-5dde3a58-2eb4-11e8-8682-6be3b37520b3.gif)

 I don't know how to fix the hover effect without getting things messy/error prone.

We'll have to work on buttons again so that border-color isn't darkened when hovering. Possibly have border-color remain the same but make the shadows more obvious or something like the following:

![peek 2018-03-23 16-11](https://user-images.githubusercontent.com/27529229/37851350-eb543932-2eb4-11e8-901d-6ecaa14c14a8.gif)

**Comment by CDrummond** [comment]
As stated, its a **very** minor niggle - and you need to look closely to see it. So, if it going to be difficult/messy/error prone - might just be better to close this issue as 'Wont Fix' and leave as is.

**Comment by godlyranchdressing** [comment]
It is a small issue and it _can_ be fixed, but the border-color change when hovering on linked buttons (which reveals the solution for linked buttons) probably shouldn't be ignored.

**Comment by CDrummond** [comment]
I like having the border darkened on hover - gives it more focus.
