### ISSUE TITLE
Revert latest button changes?

### ISSUE THREAD

**Issue by CDrummond** [ubuntu/gtk-communitheme#288]
Any chance to revert 7579503954598f9fd913b3f0a7654d3e8876ef6f ?? I **really** much preferred the look of the buttons before.

1. The side and top border of buttons is lighter now, reducing contrast
2. There's a very dark line on the bottom - which looks odd
3. On hover the button gets darker. If/when the background is darkened (#259), then I think this would make the hovered button blend in more with the background
4. The previous highlight changed the border, which was sort of consistent with the focus rect, and focus of entry fields.

Now:
![gtk3-now](https://user-images.githubusercontent.com/1141694/37867755-91792f5e-2f94-11e8-9484-b99927d204b8.png)

Before:
![gtk3-before](https://user-images.githubusercontent.com/1141694/37867760-96c97ae0-2f94-11e8-8fe8-cf2fb85bd4a0.png)

**Comment by clobrano** [comment]
Ok, I'm working on another branch to try to fix the border highlight for linked buttons. As @godlyranchdressing said it's complicated :disappointed:

**Comment by CDrummond** [comment]
But the border highlight for linked buttons seems to be just as broken now as it was before these changes. So, I'm not sure what that has to do with reverting this.

Obviously, if more people prefer the current look then fair enough.

**Comment by clobrano** [comment]
> But the border highlight for linked buttons seems to be just as broken now as it was before these changes.

That's right. Of course, having a change of the background on hover, we could remove the change in the borders (which didn't happened in that PR).

So, before showing the current state of this new branch, I'd like to explain why this fix is complicated.
As @godlyranchdressing said, in linked buttons, one of the borders (the right one) does not actually exists, so that buttons look connected. Only the last button on the right has all the 4 buttons, that's why on hover only 3 borders are highlighted.

Possible solutions
A. make the "missing" border appear on hover
B. let the shared border of the next button be highlighted as well
C. mimic border with box-shadow

Solution A and B require the linked buttons to be siblings, which does not happen always (like in page 1 of Widget Factory for instance). Using those fixes effect will cause to have randomly again an incomplete border highlight or,  worse, buttons that **change size** on hover.

![button-border-hover05](https://user-images.githubusercontent.com/2883614/37995564-2cf4ca7e-3215-11e8-9c73-7bb248ed03a8.gif)
![button-border-hover04](https://user-images.githubusercontent.com/2883614/37995566-2f052fe8-3215-11e8-97b5-0492a61c03f0.gif)


Solution C is what I want to propose. It is not as nice as the previous version (bug a part), because to avoid making the border too thick, the highlight is less dark and a bit more blurry. I tried a lot of combinations of box-shadow thickness, color, position, etc, but at the very best the highlight is more pale and blurry.

So, sorry for this long message, this is current state:

![button-border-hover01](https://user-images.githubusercontent.com/2883614/37994975-6a5e734e-3213-11e8-9b39-22511ef36e5d.gif)

![button-border-hover02](https://user-images.githubusercontent.com/2883614/37994984-6fa5a3d6-3213-11e8-903f-e8d50e525e59.gif)

![button-border-hover03](https://user-images.githubusercontent.com/2883614/37994988-718e7e5c-3213-11e8-9777-0b8be267e5c7.gif)

I understand this might be not enough, but in this case we should work on other solution (by the way OSX's buttons do not even change on over :smile: )

**Comment by CDrummond** [comment]
Your 'current state' screenshots look nice. Apart from the fact that on hover, there is an innerborder also applied - which makes the border seem thicker. Not sure I like that. Is this really required?

**Comment by clobrano** [comment]
Yes, that's the point. The Inner border is the box-shadow I added to close the border highlight on hover. We cannot get rid of the normal border, so we have actually 2 borders, one very light made by the box-shadow.

**Comment by madsrh** [comment]
Solution **C** looks good to me 👍

Without sidetracking this issue, is that the new background and backdrop color? 😃

**Comment by nana-4** [comment]
I'd prefer the solution **B**, but without change the size. Actually entry fields are doing that. :smiley:

I can help for that. Although it may conflict with #299, can I send the PR?

**Comment by clobrano** [comment]
> I'd prefer the solution B, but without changing the size. Actually entry fields are doing that. smiley

I too prefer B, but I couldn't fix the size issue where widgets are not siblings (entry fields and buttons are siblings in the examples above). If you're able to, your're welcome :wink:

**Comment by clobrano** [comment]
I wrote a message on #299 to avoid being merge while you're working on it

**Comment by nana-4** [comment]
Hmm, I could change the shared border color of _ordinary_ linked buttons (`.linked > button`),

![image](https://user-images.githubusercontent.com/9556384/38171977-b75c2668-35de-11e8-9f09-524aae27c994.png)

but linked combo buttons (`.linked > combobox > box > button`) and linked tool buttons (`.inline-toolbar > toolbutton > button`) could not be changed because their hierarchy is **too complex**. 😥

![image](https://user-images.githubusercontent.com/9556384/38171930-14f12e96-35de-11e8-8fd2-afb3e35f99b6.png) ![image](https://user-images.githubusercontent.com/9556384/38171935-2e9b5254-35de-11e8-877c-3bf5f592a237.png)

Even we can't change the border color of linked combo & tool buttons with _B_, I'm still thinking it's the best solution because linked combo & tool buttons are not so much used in actual apps.

What do you think? Is it alright?

**Comment by clobrano** [comment]
> but linked combo buttons (.linked > combobox > box > button) and linked tool buttons (.inline-toolbar > toolbutton > button) could not be changed because their hierarchies are too deep

That was my problem too.

> What do you think? Is it alright?

I don't feel it is right to ignore this problem (even if current Ambiance does it :D), this is why I tried a way that does not involve siblings widgets to highlight the borders.

I'd suggest you to look at my solution, maybe you're able to improve it, making box-shadow less pale and blurry, but keeping the same thickness. Of course, if you like

**Comment by nana-4** [comment]
> I don't feel it is right to ignore this problem

I personally feel it can be ignored as a _minor_ bug. (At least it's quite rare for the linked _combo_ buttons to be used in the gtk apps, even if it is used on `Page 1` of `gtk3-widget-factory` :D)

I also feel the inner box-shadow effect will look quite buggy, no matter how hard we try. At least I think A is better than C (if you think B is no longer an option).

**Comment by nana-4** [comment]
Okay. Although I pushed the PR above, now I'm thinking of another solution.

As we already know, it's technically hard and painful to change the linked button's border color according to the states. So I would like to propose changing the button states without changing the border color.

This is the reworked button that I would like to propose:
![peek 2018-04-02 22-21](https://user-images.githubusercontent.com/9556384/38197775-e12a11ee-36c4-11e8-8d8c-4e951f6348e8.gif)

Although it changes only the background color on hovering, I adjusted it to make it easy to notice.

How do you think of this?

**Comment by CDrummond** [comment]
The shadows under buttons are too strong - especially on combo buttons. The sunken shadow is also much less. Really the buttons as stated to revert to were **much** nicer.

**Comment by Feichtmeier** [comment]
I don't feel that the shadow is too strong. +1 from me for the latest button changes
I generally like the idea of only changing the hovered background and not the border

**Comment by CDrummond** [comment]
Only personal opinion (and I'm no designer) - I'm fine with the darker button, but I preferred the original shadows (the external ones).

Eitherway, I think someone (and not me, as I'm not qualified) needs to make a definitive statement of what they should look like, implement and move on.

**Comment by clobrano** [comment]
@nana-4 it is not clear now which changes this last 2 PRs of yours brought respect my original bright button version and the next one made by @godlyranchdressing, a part, I guess, the removal of wrong border highlights

**Comment by nana-4** [comment]
@clobrano Well, I'm not very sure what you mean though.. #304 was just a try to solve the linked border problem without changing the current button design. Nothing more, nothing less.

IMHO, I personally prefer the a little darker buttons like Unity8 design (as @godlyranchdressing suggests/recommends) rather than the bright buttons without a darker bottom-border. (Although it may be a very personal opinion, I can feel _Ubuntu_ from the darker one, but cannot feel it from the bright one. 🤨)

If you and other designers are OK, I hope to merge my redesigned (or restored?) button style.

**Comment by nana-4** [comment]
Once I rephrase/summarize again, _to me_ the problems with white buttons are:

- too bright for my eyes (even if the background is light gray)
- easy to mistake as entry fields (especially on the linked buttons/entries)
- (if we decide not to change the border color) it's destined to make its background darker on hovering, since "white" is the brightest color
- less look like Ubuntu/Suru/Unity8

> Off the top of my head, I would say the gray buttons (as we initially had) will look less modern.

For the initial buttons, I agree with that. But my reworked button is much _brighter_ than that and IMHO it looks much modern. :D

**Let's line up for comparison:**

My proposal:
![image](https://user-images.githubusercontent.com/9556384/38234772-d1b7b104-3759-11e8-8b96-8deb887294b5.png)

Initial style:
![image](https://user-images.githubusercontent.com/9556384/38234612-58ace2a2-3759-11e8-92dc-097bd010860b.png)

Previous style _with light gray background_:
![image](https://user-images.githubusercontent.com/9556384/38234543-25bd41f2-3759-11e8-9c9e-8ac934a2960a.png)

Current style:
![image](https://user-images.githubusercontent.com/9556384/38234480-f7c7b174-3758-11e8-8962-def60afeb976.png)

@clobrano's PR (#299):
![image](https://user-images.githubusercontent.com/9556384/38234358-9d3af5cc-3758-11e8-9da6-08b4f2980b5c.png)


To remind; My proposal was made as a solution of the border color issue (and other various problems).

**Comment by CDrummond** [comment]
In most of the screenshots above, the combobox entry and entry field buttons have a shadow whilst the rest of the widget does not. This looks a little odd to me. What about placing the button inside the entry field? Kind of like the -/+ buttons on the spin boxes. e.g.

![btns](https://user-images.githubusercontent.com/1141694/38236492-34b12850-371c-11e8-9c10-5ae1f3b97f84.png)

(This is just a quick mockup up, ignore the disabled combo)

**Comment by nana-4** [comment]
@CDrummond  It's technically quite hard. `spinbutton`'s inner structure is special, but normal buttons are not.

The biggest issue is the focus ring:
![peek 2018-04-03 17-31](https://user-images.githubusercontent.com/9556384/38238452-dd880d52-3764-11e8-8514-40472115d3b9.gif)

I personally feel we should not do that.

**Comment by clobrano** [comment]
Sorry, I've been sick these days and couldn't keep up with these discussion.
It's complicated to come up with a decision, because I do want it to be definitive.
Summing up, @nana-4 proposal looks good to me, even if:

1. I still prefer the clicked state or "Previous style with light gray background". It's very clear that the button is pressed, while @nana-4's proposal the button shadow is not enough (I understand that this change has been made because the theme is mostly flat, but still)

2. The last month of development has been spent to avoid gray buttons :smile: . I take into account that the buttons might be too bright, but so I think that maybe it is better a darker background that a darker button, since most of the space is occupied by the first.

**Comment by clobrano** [comment]
How cool is that OSX doesn't even bother making any hover animation on buttons 😄 ?

Anyway, I tried some updates on my branch, replacing the border change with a slight darker background

![button-style-new-again](https://user-images.githubusercontent.com/2883614/38307364-cc683880-3813-11e8-93b1-91e8a8f765b7.gif)

**Comment by madsrh** [comment]
@clobrano The only thing is the hover color is very similar to the background.

**Comment by clobrano** [comment]
Yes, because background is still quite bright (#F7F7F7). What if we just work with shadow
![button-hover-new01](https://user-images.githubusercontent.com/2883614/38325172-8b5c5554-3842-11e8-9599-81d1b3d81192.gif)

**Comment by madsrh** [comment]
@clobrano This LGTM

**Comment by godlyranchdressing** [comment]
Am I the only one who doesn't like the white buttons? As usual, I can live with it, but the white buttons look too much like macOS' for me. :man_shrugging: 

The #F2F2F2 in @nana-4's mockup looks like a good middle ground.

**Comment by clobrano** [comment]
> white buttons look too much like macOS' for me.

Let me try with that color again, but I think that probably a bg change would be needed as well

**Comment by clobrano** [comment]
Button #F2F2F2
![button-hover-new02-btnf2f2f2](https://user-images.githubusercontent.com/2883614/38335521-e1795150-385e-11e8-8e4d-0d377317c754.gif)

Button #F2F2F2 + BG #EBEBEB
![button-hover-new02-btnf2f2f2-bgebebeb](https://user-images.githubusercontent.com/2883614/38335543-f01ebad8-385e-11e8-9c77-5714d0e15513.gif)

**Comment by nana-4** [comment]
> Am I the only one who doesn't like the white buttons?

Me too :slightly_smiling_face: Actually I was a fan of the initial style of the buttons. (Indeed it looked a bit less modern, though.)

@clobrano IMHO, the only subtle `box-shadow` change on hovering may be not easy to notice. I'd still prefer the `background-color` change of my proposal.

> I still prefer the clicked state or "Previous style with light gray background". It's very clear that the button is pressed, while @nana-4's proposal the button shadow is not enough (I understand that this change has been made because the theme is mostly flat, but still)

(Sorry for the late reply.) Indeed the shadow will be changed slightly, but instead the background will be much darker. And IMHO it looks enough clear that the button is pressed. Although I can live with the big blurred inner shadow, I'd still feel it looks like out of place. :)

**Comment by Feichtmeier** [comment]
I would prefer the white ones. Gives a better contrast on the background

**Comment by clobrano** [comment]
> @clobrano IMHO, the only subtle box-shadow change on hovering may be not easy to notice.

I am not sure is really necessary to be so evident, but I agree that your solution looks cleaner at the end. White background on button is hard to style on hover (and in fact OSX doesn't style it at all, last time I said that, promise :smile: )

So, we can go ahead with @nana-4's PR for me, could you just try add this?

> I still prefer the clicked state or "Previous style with light gray background".

**Comment by nana-4** [comment]
I tried that clicked state:

![image](https://user-images.githubusercontent.com/9556384/38370242-9d91480a-3924-11e8-9ef0-01f773a602e1.png)

How about this? 
@clobrano @madsrh @godlyranchdressing @Feichtmeier and others?

**Comment by Feichtmeier** [comment]
Looks quiet good. Do we plan to try the exact same toggled/clicked state shadow on dark buttons in the header bar? 

There was a time when they both looked very alike (apart from the color ofc) which have me a feeling of consistency.

**Comment by clobrano** [comment]
@Feichtmeier I'd say yes, even if shadows on dark backgrounds does not usually work fine as well

**Comment by clobrano** [comment]
@nana-4 is the last content you posted coming from #304?

**Comment by nana-4** [comment]
I'm really sorry for my long silence. I had trouble in my real life and couldn't looked at this at all.

@clobrano No. I have created a new PR, so I will close the old PR.

**Comment by CDrummond** [comment]
Should this now be closed? I'm OK with the current button look - so no need to revert anything.
