### ISSUE TITLE
Toggled item in header bar not clearly visible

### ISSUE THREAD

**Issue by CDrummond** [ubuntu/gtk-communitheme#302]
The currently toggled item in a GtkHeader bar is not clearly visible/highlighted.

e.g. in this screenshot the magnifying glass icon has been pressed to produce the search field. However, its state is not indicated very clearly - dark on dark is not the best indicator. Perhaps it should have a lighter background?

![screenshot from 2018-04-01 09-58-48](https://user-images.githubusercontent.com/1141694/38171533-61f5288c-3593-11e8-8017-f24e82ecfd8c.png)

**Comment by CDrummond** [comment]
This issue was originally raised by Kvantum's author. He's currently working on a matching Qt style. To mimic headerbars he's suggesting that the main toolbar in a Qt's app have a dark background. Hence the issue with toggled items not being clear. Currently he's implemented the following solution:

![screenshot from 2018-04-01 14-15-13](https://user-images.githubusercontent.com/1141694/38173503-555422d0-35b7-11e8-96a5-1d7be8b9422f.png)

where the toggled items have the orange underline. Not sure if this matches up with waht Communitheme is aiming for?

**Comment by tsujan** [comment]
I completely agree with @CDrummond; `Ambiance` had a similar problem. The header-bar is elegant. The hover color of buttons is OK too. But the pressed state can't be seen clearly. I don't know whether that could cause a problem in GTK3 apps (can their header-bar buttons have a toggled state?) but a matching Kvantum/Qt theme with that pressed state would be a disaster ;)

**Comment by madsrh** [comment]
I don't know if you followed [this discussion](https://community.ubuntu.com/t/mockups-new-design-discussions/1898/220) earlier, but yes I agree that current header-bar buttons still isn't very easy to spot when pressed. 

I suggested a orange line [back in november](https://community.ubuntu.com/t/design-mockups-updates-designer-only/2053/13).

Another option would be to keep the gray hover color and simple add the inner shadow / 3D look when pressed. I'm sorry for this very rude mockup, but hopefully you get my point:

![asdf](https://user-images.githubusercontent.com/3986894/38178630-21c9e55c-3617-11e8-9487-84c9e1110d64.gif)

**Comment by tsujan** [comment]
> I suggested a orange line back in november.

That's very nice.

> Another option would be to keep the gray hover color and simple add the inner shadow / 3D look

IMHO, this isn't elegant but tastes differ.

**Comment by Feichtmeier** [comment]
@CDrummond  Isn't this the exact thing you wanted in https://github.com/ubuntu/gtk-communitheme/issues/260 ?
I am confused :D 

___________

Anyways, I think the orange underline is a nice idea, maybe with a simple dark grey background without a gradient or shadow?

**Comment by CDrummond** [comment]
@Feichtmeier Not sure how this related to #260 - this was with buttons that had no border, hence looked a little blurry, due to shadow. That was with buttons on a light background.

This issue is stating that when a button is toggled, its not very visible. How does this relate to having/not having a border? Currently there is a dark border against a dark background - not exactly very clear.

**Comment by tsujan** [comment]
> Currently there is a dark border against a dark background

And light border against a dark bg would be ugly, although visible. With this semi-flat theme, the best solution would be an orange underline, IMHO.

**Comment by tsujan** [comment]
BTW, and not related to this: I'm curious why menus are light? Wouldn't a dark menu -- like that of Ambiance -- be more elegant? Sorry if that's already discussed and decided.

**Comment by CDrummond** [comment]
Menus are currently dark - but there is a discussion/issue about changing to white. To stop a 'wall of black' at the top of the screen.

One plus point for the underline, is that it is consistent with the chosen path bar item and menubar item.

**Comment by Feichtmeier** [comment]
@CDrummond after the addition of the 1px black border on toggled/pressed/selected buttons in the header bar 1px of was "stolen" from the shadow :dancing_women: 
Anyways we all agree that the current implementation needs work :)
I'll try to implement @madsrh orange line and post some screenshots

**Comment by CDrummond** [comment]
@Feichtmeier but just having the shadow was not very clear! A more definitive toggled state is required (IMVHO)

**Comment by tsujan** [comment]
> Menus are currently dark

I updated it yesterday:

![menu](https://user-images.githubusercontent.com/981076/38201181-8dc5cdee-36ac-11e8-8fbf-dee486bc647a.png)

You meant menubar, not menu? If the gnome-shell theme has dark menus, it's better for this theme to have them too (sorry, I don't have gnome-shell to check that). Anyhow, menus may need opening another issue.

And I see all of us agree with an underline.

**Comment by Feichtmeier** [comment]
@clobrano  Yes I agree :)

Just looked into it... and my css skills end right here :D @clobrano you are needed here

button, button.flat {
      @each $state, $t in ("", "normal"),
                          (":hover", "hover"),
                          (":active, &:checked", "active"),
                          (":disabled", "insensitive"),
                          (":disabled:active, &:disabled:checked", "insensitive-active"),
                          (":backdrop", "backdrop"),
                          (":backdrop:active, &:backdrop:checked", 'backdrop-active'),
                          (":backdrop:disabled", 'backdrop-insensitive'),
                          (":backdrop:disabled:active, &:backdrop:disabled:checked", 'backdrop-insensitive-active') {
                            &#{$state} { @include button($t, $c, $tc, $flat:true); }
      }

      @each $b_type, $b_color in (suggested-action, $success_color),
                                  (destructive-action, $destructive_color) {
        &.#{$b_type} {
          // special buttons show their color when not interacted with
          @each $state, $t in ("", "normal"), (":hover", "hover"),
          (":active, &:checked", "active"), (":disabled", "insensitive"),
          (":disabled:active, &:disabled:checked", "insensitive-active"), (":backdrop", "backdrop"),
          (":backdrop:active, &:backdrop:checked", 'backdrop-active'), (":backdrop:disabled", 'backdrop-insensitive'),
          (":backdrop:disabled:active, &:backdrop:disabled:checked", 'backdrop-insensitive-active') {
            &#{$state} { @include button($t, $b_color, $tc, $flat:true); }
          }
        }
      }
    }

@CDrummond @madsrh 
So in the headerbar we would have:

- unpressed and not toggled buttons
- pressed buttons 
- toggled buttons

Should pressed normal buttons and toggled buttons both have the orange line?
The orange line is also present in the GtkStackSwitcher so they would fit quiet good to the togglbuttons.

**Comment by tsujan** [comment]
> Should pressed normal buttons and toggled buttons both have the orange line?

IMO, that would be better.

**Comment by CDrummond** [comment]
@tsujan GNOME shell uses dark dialogs, etc, the Gtk theme does not. The shell, and its dialogs, should (and do) look different to apps - as it is different. Its dialogs deliberately look different so that you know you are interacting with it, and not an app.

Menus have always been white with this theme. I thought you mean menubar (my mistake), and there is an issue to make this also white-ish.

**Comment by tsujan** [comment]
> Only to be sure that we are talking about the same thing

@Feichtmeier I think we're talking about the same thing. This screenshot shows a selected pathbar item and a pressed button -- the former is excellent while the latter lacks visibility -- and it's better to make buttons look like pathbar items when toggled by adding an orange underline to them (the presed state could be made like the toggled state too if you agree):

![headerbar](https://user-images.githubusercontent.com/981076/38202561-66071632-36b1-11e8-84f8-46d6b2d09c01.png)

**Comment by godlyranchdressing** [comment]
@tsujan I wish we could just add an orange underline, it's the first solution that comes to mind for me, but the border-radius will lead to the orange underline being curved as well. The stackswitcher uses a hack that I don't think would be possible to replicate for regular buttons.

![border](https://user-images.githubusercontent.com/27529229/38278972-46e65086-376c-11e8-9c32-826bffeb66ee.png)

**Comment by Feichtmeier** [comment]
@godlyranchdressing wouldnt this one work?

background-color: none;
color:white;
border-left: none;
border-top: none;
border-right: none;
border-radius: 0px 0px 0px 0px;
border-color: $selected_bg_color;
border-bottom: 2px solid $selected_bg_color;

Works in the shell's calendar atleast :) But buttons are different I guess, total button noob here

**Comment by madsrh** [comment]
Does it need to have a dark (pressed) background too or is the line sufficient?
Like @Feichtmeier is suggesting, losing the squircel background and border and only having the orange line underneath like the old [mockup ](https://ubuntucommunity.s3-us-east-2.amazonaws.com/original/2X/1/1032ac8f86509e470f56698f91d2c4b947d7117f.jpg).

**Comment by tsujan** [comment]
> Does it need to have a dark (pressed) background too or is the line sufficient?

The line is a practical must, IMHO, but only the designers of Communitheme (developers and contributors) could decide about a background :)

**Comment by madsrh** [comment]
@tsujan :grin: We will let @godlyranchdressing decide then :wink:

**Comment by godlyranchdressing** [comment]
@Feichtmeier that would work, but we'll also need to have `border-bottom-width: 2px` for unchecked buttons and that'll lead to what might be too many allowances (to me) and possible complication.

Trying @madsrh's suggestion, but with the text color being transparentized (like it is with some Shell elements) when the button is active/checked.
![lines](https://user-images.githubusercontent.com/27529229/38279756-cb920df4-376f-11e8-9a50-bf8ab3f10224.gif)

Unfortunately, I don't think it looks as elegant when it comes to text buttons.
![text](https://user-images.githubusercontent.com/27529229/38279826-245ff36a-3770-11e8-991b-21808f4e7d78.png)

**Comment by tsujan** [comment]
> .... but with the text color being transparentized

Adding an underline shouldn't affect the text. I think Adapta has it, plus nice animations....

**Comment by madsrh** [comment]
I tried Adapta and a few other theme, that uses the colored line underneath and IMO this is a half baked solution. I still prefer the solution I suggested earlier. This is what it would look like (some tweaking is required of course)

` .popup:checked { background: #5d5d5d; } `

![pressed](https://user-images.githubusercontent.com/3986894/38292256-5a551ab8-37e3-11e8-997f-14db57845d14.gif)

**Comment by tsujan** [comment]
@madsrh That looks good too -- if it has no side effect -- but, frankly, an orange underline will be much better, especially because it's also used in selected header-bar items.

> IMO this is a half baked 

Why? There should be a safe way of adding an underline there. Doesn't gtk3 allow that?

Sorry that I can't be of any help -- I stopped making gtk3 themes since gnome-3.4 and just maintain one theme.

**Comment by clobrano** [comment]
@madsrh [mockup](https://github.com/ubuntu/gtk-communitheme/issues/302#issuecomment-378497684) is similar to what we had. Somehow it got lost with latest changes.

This might bring some complaints :smile: but I propose it as well

![image](https://user-images.githubusercontent.com/2883614/38294032-e25e62ba-37e9-11e8-8cd3-16641c7fa295.png)

![image](https://user-images.githubusercontent.com/2883614/38294068-0196693e-37ea-11e8-97e2-5391f202caac.png)

otherwise

**Comment by tsujan** [comment]
> especially the text buttons as @godlyranchdressing pointed out.

@madsrh That was caused by text translucency; wasn't it? An underline shouldn't affect the text if it's drawn correctly -- or gtk has an issue?

> but the line looks less clean to me.

When it comes to a graphic design, we should accept the fact that taste might differ surprisingly ;) So, we could only rely on votes, IMHO. To me, it's very clean.

@clobrano

Again, different tastes. To me, that border is an overkill.

> otherwise, but it might be too subtle anyway

Not clearly visible again.

**Comment by Feichtmeier** [comment]
That's why I asked about the difference between toggle buttons and pressed normal buttons. With the current idea, no matter in which version, all buttons are somehow similar. And I think this is good. With the underline they stop being regular buttons to me. I don't know if anyone else feels this way?
When I look at the orange underline without this context it looks really great and ... elegant ... But in the context it hardly makes sense to me now

**Comment by madsrh** [comment]
How about something like this:
![peek 2018-04-04 01-31](https://user-images.githubusercontent.com/3986894/38297228-9d155dd0-37a8-11e8-85ab-4bc0d03440f5.gif)

`.popup, .image-button, .text-button { background: #393737; }
.popup:hover, .image-button:hover, .text-button:hover  { background: #5d5d5d; border: #3d3d3d; }
.popup:checked { background: #5d5d5d; border: #222; }`

I don't know why the inner shadow is so slow

**Comment by nana-4** [comment]
Sorry for the stupid question, but was the **current** headerbar button style changed _intentionally_? I thought it was changed _accidentally_.

In any case, I personally like the previous headerbar button style (without a border) the most so far.

**Comment by clobrano** [comment]
> Slightly related, what happened to this (background for buttons in headerbar)

Sorry, in backlog as well :disappointed: 

> Sorry for the stupid question, but was the current headerbar button style changed intentionally? I thought it was changed accidentally.
In any case, I personally like the previous headerbar button style (without a border) the most so far.

Confirm the accidentally, it was very similar to last @madsrh mockup

**Comment by nana-4** [comment]
> Confirm the accidentally, it was very similar to last @madsrh mockup

Yeah, except for the background of normal status ;)

**Comment by tsujan** [comment]
> In fact, in my branch with the attempt to revert last button change, this is the effect

The user still couldn't discern these toggled buttons easily.

**Comment by Feichtmeier** [comment]
@clobrano this looks very good. I am little bit confused though, are you and @nana-4 working on the same issue? :dancing_men: 

I would be totally for removing the black border again. 
This looks really strange and out of design. Especially since the removal of the red circle.
Now when you press a button suddenly there comes
A red circle
A grey squircle background
+ The black border
I feel that this black border is really too much. Was never a fan of it tbh =)

**Comment by nana-4** [comment]
@Feichtmeier Not yet, sorry. I tried to remove the black border with #331, but the current button styling is more complicated than I expected, so I decided to postpone it for now. I agree with you, though. :)

**Comment by madsrh** [comment]
> Yeah, except for the background of normal status ;)

@nana-4 I was trying out background for normal status for issue [152](https://github.com/ubuntu/gtk-communitheme/issues/152). If you ignore that normal background, what do you think about it? Keeping the gray for pressed state and just adding the box-shadow.

**Comment by nana-4** [comment]
@madsrh IMHO, the slightly light buttons (for normal state) don't look clean. I also imagine that users may misunderstand it is a bug. (Although I personally feel #152 is a quite minor issue,) I'd prefer to make the text/icon color of normal buttons slightly dim like this:
![image](https://user-images.githubusercontent.com/9556384/38719392-b60d2dbe-3f2c-11e8-9bd2-d9d0a256e2db.png)

**Comment by madsrh** [comment]
@nana-4 You might have a point, but you avoided the question 😆

> If you **ignore that normal background**, what do you think about it? Keeping the gray for pressed state and just adding the box-shadow.

![image](https://user-images.githubusercontent.com/3986894/38720520-d2b41b66-3ef6-11e8-9aed-2eac115faf83.png)

😄

**Comment by nana-4** [comment]
@madsrh Sorry, I didn't understand the meaning of the question well.

I'm not against the pressed button style. It looks very good to me. I just thought the _normal_ (slightly light) background doesn't look very good to me. :sweat_smile:

**Comment by madsrh** [comment]
I cannot describe how frustrating it is not to be able to push a PR for something as simple as a background change 😫 Anyway, @nana-4 could we try this "keeping the hover gray and adding box-shadow when checked"?

**Comment by madsrh** [comment]
Or @godlyranchdressing could you try changing the background to stay gray in the checked state?

**Comment by godlyranchdressing** [comment]
@madsrh When you say gray, do you mean the hover background color?

**Comment by clobrano** [comment]
@madsrh I tested the bright background with box-shadow and no black border, but I'm not sure it could work well enough because the dark background make any shadow almost invisible. What do you thing about removing the box-shadow and keeping the bright gray?

![image](https://user-images.githubusercontent.com/2883614/39193138-26d3503a-47db-11e8-87a3-52709879b7d7.png)

here toggled button is 5% brighter than hover

**Comment by madsrh** [comment]
@clobrano This looks **much** better! 👏

**Comment by godlyranchdressing** [comment]
The inconsistency of that bothers me though. If we do that, then I'm leaning towards just removing the use of shadows in buttons everywhere. :man_shrugging:  

Taking some cues from from the shell is another option though. We could borrow the hover and active effect from the config/lock/shutdown buttons in the system menu popover. Either way, the hover and checked/active state will need to be different somehow.

**Comment by tsujan** [comment]
A shadow should be dark to look like a shadow. When that background is too dark, "shadows" wouldn't be visible, unless with a screen magnifier ;)

**Comment by Feichtmeier** [comment]
@godlyranchdressing personally after watching on and working with this theme daily I think there is a style mismatch between the 3d pressed buttons and all other elements. All other elements are flat. So I would welcome such flatness =P

**Comment by madsrh** [comment]
Maybe I was a bit too fast with my reply. I like the flat look - it looks more modern, but the benefit of using shadow is that it's easy to understand when the button is pressed. Like this (blurry) one:
![image](https://user-images.githubusercontent.com/3986894/39208740-22d34912-4804-11e8-8b35-48da55ec50f8.png)
Perhaps is the background what a bit brighter than the hover color? 🤔 

I agree with @Feichtmeier that there's a bit of a button style mismatch.

From [what I've seen](https://material-design.storage.googleapis.com/publish/v_1/quantumexternal/0Bx4BSt6jniD7bEFqalRSeUJkbEU/components_buttons_main14.png), there's no really good way to show the pressed state with flat design. Themes like Arc, Matcha does exactly what @clobrano did above (just with less soft colors).

![image](https://user-images.githubusercontent.com/3986894/39210406-e50dea9c-4808-11e8-8ac5-ea584c1f8e4c.png)

I actually like the inner shadow we have now, if just the black border was removed (perhaps a brighter background to emphasize the shadow). 
@godlyranchdressing do you really want to change all the buttons to flat design? I have to admit that back in november I had no idea that there would be SO many edge cases and corner cases for buttons 😄

**Comment by godlyranchdressing** [comment]
@madsrh I'd rather make everything flat than have there be a mix. I'll try with some mockups based on the original Unity 8 style and [nana-4's proposal](https://github.com/ubuntu/gtk-communitheme/issues/288#issuecomment-378155296) for regular buttons. 

I don't mind flat design and I can live with it if we go towards it, but having another flat theme just seems kind of expected (but I'm also biased because I really like the cross between flat and skeuomorphic). 

Unity 8 style:
![38199173-b8b35b70-36ca-11e8-9d3e-ff18a150b45f](https://user-images.githubusercontent.com/27529229/39226534-12720dfc-4821-11e8-8d97-becb044ddaee.png)
![38199172-b782e61c-36ca-11e8-88b8-796dacdf9630](https://user-images.githubusercontent.com/27529229/39226535-12960676-4821-11e8-957a-8b301f98317e.png)

**Comment by madsrh** [comment]
Sound great @godlyranchdressing 👍I can't wait to see what you come up with 😄

My only issue with nana-4's proposal is that buttons get brighter on hover. While this makes sense because it can also be applied in the headerbar, it just feels odd to me.

**Comment by clobrano** [comment]
I fear that unity8 style doesn't differentiate enough between standard and pressed. What about making it darker when pressed?

**Comment by Feichtmeier** [comment]
@godlyranchdressing this could become the final fit for this theme =)
I think our theme is still outstanding from others even if it is flat, too.

**Comment by NusiNusi** [comment]
one stupid question here... pretty sure this was already discussed and i could not find it. The topbar has a new PR which uses transparency for the topbar when the window is maximized.
Could the gtkheaderbar get the same transparency too? The buttons could keep their color and this way could be easier recognized as buttons:
![peek 2018-04-25 13-01](https://user-images.githubusercontent.com/36449926/39242166-5d1a7d0e-4889-11e8-8c07-0db1170efe6f.gif)
So transparency for gtkheaderbar + non-transparency for the clickable elements (buttons) in the dark headerbar.

**Comment by NusiNusi** [comment]
okay, forget about it :smiley: 
Let's see what @godlyranchdressing is preparing.

**Comment by clobrano** [comment]
@NusiNusi I'm trying to trace all the places where you ask the same things :grinning: 
Please, just ask once and in one place

**Comment by godlyranchdressing** [comment]
Much cleaner pressed button effect without so much blur. 

![peek 2018-04-25 10-20](https://user-images.githubusercontent.com/27529229/39251870-4eceaa20-4872-11e8-9c48-69569b2384fc.gif)

(@madsrh I think the brightness increase looks especially weird now that you mentioned it :laughing:)

I'm guessing that @nana-4 used a darker border-top-color along with a very slight box-shadow. If you use box-shadow's blur property then all sides of the button (annoyingly) gets a shadow and that's mainly what causes the blurriness.

Rough CSS for the above. I just copied and pasted the CSS I used in the inspector. 
````button:active, button:checked { 
box-shadow: inset 0 1px 1px 0px rgba(0, 0, 0, 0.05); 
border-top-color: #aaa;
background: #d8d8d8 }
````

Headerbar text buttons looks much better IMO:

![peek 2018-04-25 10-23](https://user-images.githubusercontent.com/27529229/39252006-acffc46c-4872-11e8-9904-8fbe46d62b5a.gif)

Image buttons in the headerbar might still have some issues, but it looks a little better to me.
![peek 2018-04-25 10-24](https://user-images.githubusercontent.com/27529229/39252056-cc91de46-4872-11e8-94f3-7ac2d880661b.gif)

Rough CSS for both:

```
headerbar button:hover { 
background: #555252; 
border-color: #555252; 
}

headerbar button:active, headerbar button:checked { 
background: #484545; 
border-color: #282525; 
box-shadow: inset 0 1px 1px 0px rgba(0, 0, 0, 0.15); 
border-top-color: black
}
```

For the headerbar it's pretty much the same thing, darker top border when pressed + slight shadow (though the alpha value used is slightly more for the headerbar: 0.05 vs 0.15). I also brought back the border since you can see a slight gap between the top border and left and right borders without it:
![borde](https://user-images.githubusercontent.com/27529229/39252423-9b29e9d8-4873-11e8-96a3-3b04a13c49fc.gif)

I'm sure things can be finetuned a bit more.

**Comment by clobrano** [comment]
Awesome work!

**Comment by ya-d** [comment]
Well done, much better than the soft blur!

Adding one more point to Feichtmeier's to think about: Maybe the border of the pressed button should be a bit darker to keep the contrast similar to 'normal' buttons (against the now darker background). Currently the border visually fades away when the button is pressed. Would also make sense from a lighting perspective to me because the light breaks at the recessed edge and casts a shadow. (So maybe the border could even be a tiny bit stronger than for regular buttons.)

**Comment by madsrh** [comment]
@godlyranchdressing Isn't background: #484545; a little too close to the headerbar background color? IMO I would want something **only slightly darker** than the hover color.

**Comment by godlyranchdressing** [comment]
@madsrh The PR (#366) uses #524e4e for hover #4d4949 for active.

![pr](https://user-images.githubusercontent.com/27529229/39281110-0d0231f2-48d1-11e8-9b53-fcf3b22c5f34.gif)

The pressed effect doesn't show as much as it should because a line is being ignored for some reason, so I left it open for review. I don't know what I'm missing.
