### ISSUE TITLE
System Monitor does not seem to respect Communitheme

### ISSUE THREAD

**Issue by sumeetaras** [ubuntu/gtk-communitheme#315]
I opened System Monitor on the Ubuntu 18.04 daily build with Communitheme and it is showing Adwaita theme instead of Communitheme. I have installed the communitheme from the ppa and logged into 'Communitheme on Xorg' session.

See attached
![testscreen](https://user-images.githubusercontent.com/10984081/38338767-fe412856-3838-11e8-9946-98e43f20bed9.png)

**Comment by Feichtmeier** [comment]
This happens because

- since some days the system monitor is beeing installed as a snap
- snaps only support ambiance and adwaita at the moment (very very soon [https://community.ubuntu.com/t/snapping-communitheme/4890/6] this theme here will be supported in snaps)
- adwaita is the fallback theme 

Just wait some weeks or remove this snap and install the other version with apt :) Best wishes and thanks for reporting do not hesitate to report any further issues

Closing this as this is not directly related to this repo
