### ISSUE TITLE
Save dialog enhancements

### ISSUE THREAD

**Issue by madsrh** [ubuntu/gtk-communitheme#357]
I don't have the answer for this one, but whenever I see the save dialog, I always think it looks a bit off 🤔 

- The textfield where you have to type the filename is almost impossible to spot if it isn't selected. Maybe the background is just inherited from the darkmode. Perhaps this should be white as it is in Ambiance?

![image](https://user-images.githubusercontent.com/3986894/39156409-45d09f22-4756-11e8-9797-45648c1bc92d.png)

- The "browser-header-stack" panel looks weird being white when there's a table header with a lightgray background below - looks like something went wrong. Here I tried to make it darker. Is it too many shades of gray? Perhaps just use the sidebar color?

![save](https://user-images.githubusercontent.com/3986894/39156469-87ce360a-4756-11e8-964e-1bd7488095ab.gif)

**Comment by madsrh** [comment]
@clobrano You don't like the white background? IMO the hover background is still too dark

**Comment by clobrano** [comment]
Unfortunately white background is so strong that selection ring is no more visible. This way the entry looks visible to me, fixing the original problem, without distracting because if it's not selected, my attention is actually elsewhere in the window.
Not to forget that the entry is the first thing selected when window opens, so the user should be able to understand what it is and how to use it. What do you think?

**Comment by madsrh** [comment]
> Unfortunately white background is so strong that selection ring is no more visible. This way the entry looks visible to me, fixing the original problem, without distracting because if it's not selected

I agree @clobrano! Although it's a small improvement, the hover background is an improvement for sure.

What do you think about the "browser-header-stack" panel?

**Comment by clobrano** [comment]
> What do you think about the "browser-header-stack" panel?

Uhm, darker because the pathbar is already the same color of "name" row below, right?

**Comment by clobrano** [comment]
Alright, this actually requires some time, since all the path-bar inside a filechooser is to be restyled :smile: 
I'll work on it

**Comment by clobrano** [comment]
Worth a try

**Comment by madsrh** [comment]
Nope - the hover background color is better.
![image](https://user-images.githubusercontent.com/3986894/39269140-547e89ee-48d2-11e8-8485-0c9c624d588f.png)

Totally unrelated: did you notice the blurry edge of the Gedit over Nautilus? I was wondering if a border would fix this or what do you think?
![image](https://user-images.githubusercontent.com/3986894/39269459-2b30077e-48d3-11e8-9db6-f8cd4a4594cf.png)



...But here's a fix @NusiNusi 🤣 
![image](https://user-images.githubusercontent.com/3986894/39269123-3f40a292-48d2-11e8-88be-751006b787d3.png)

**Comment by NusiNusi** [comment]
as long as all entryfields look the same i am happy. buuuuuut the white entryfield somehow "eats" the orange. The orange is this way for me not so strong visible anymore. dark entryfield looks IMHO better.

**Comment by madsrh** [comment]
Okay, it was a bad joke @NusiNusi - sorry. Carlo already killed the white fields 💀 

I'm not sure if we can use the same color - it just doesn't look good. I would love to see them unified, but I would rather they look great but differently styled. Also, they are not exactly the same thing: one is a shell dialog and the other is part of the GTK theme.

**Comment by Feichtmeier** [comment]
@clobrano I've found one additional issue which you could resolve with this:
![image](https://user-images.githubusercontent.com/15329494/39301381-22a9dc84-494f-11e8-8ef9-bf0394367cee.png)
The color of the text should be black

**Comment by godlyranchdressing** [comment]
The white entry field looks better than I thought it would! The only problem is it overpowering the orange. Though the following is still an option. I mentioned this to fix the strange "orange border with blue text selection" inconsistency. Just rely on caret-color instead of border-color. Maybe this is too muted though.

![entry](https://user-images.githubusercontent.com/27529229/39311777-da6ce2c6-493b-11e8-9d99-ff23c940b8df.gif)

**Comment by clobrano** [comment]
I feel white entry in headerbar is a bit too much. I came up with this now

![image](https://user-images.githubusercontent.com/2883614/39314762-4a5dee52-4975-11e8-864c-a20a77d78f74.png)
![image](https://user-images.githubusercontent.com/2883614/39314784-59cbedf8-4975-11e8-8632-609ea3188f66.png)

**Comment by clobrano** [comment]
@NusiNusi :open_mouth: 
Both pictures come from the change, but those are just static pictures, the interaction with the filechooser is clear, the only problem was that originally, unselected entry in headerbar was not really visible.

When you open the file chooser, the entry is selected and text is highlighted, so you cannot misunderstand it for a window title.

**Comment by clobrano** [comment]
> Totally unrelated: did you notice the blurry edge of the Gedit over Nautilus? I was wondering if a border would fix this or what do you think?

Gedit is blurred there because the filechooser is opened. I don't feel like is necessary to sharpen it

> The white entry field looks better than I thought it would! The only problem is it overpowering the orange. Though the following is still an option. I mentioned this to fix the strange "orange border with blue text selection" inconsistency. Just rely on caret-color instead of border-color. Maybe this is too muted though.

@godlyranchdressing 
I am not very happy with the first image opening filechooser (black from the headerbar, orange ring, light blue text selection, a very clash of colors :disappointed: ), so I am trying what you proposed, only I cannot get rid of orange selection. Is it the `outline-color` property, right?

**Comment by Feichtmeier** [comment]
Linking the same issue into this: https://github.com/ubuntu/gtk-communitheme/issues/295

**Comment by clobrano** [comment]
With the recent changes in text selection, this looks a bit better even with selection ring

![image](https://user-images.githubusercontent.com/2883614/39529717-a35742fe-4e27-11e8-9bd9-d4ded41266ad.png)
