### ISSUE TITLE
Orange in close button

### ISSUE THREAD

**Issue by godlyranchdressing** [ubuntu/gtk-communitheme#369]
While I _did_ like the orange background before, I think if we're removing it then it should be completely removed instead of having it only show up when hovering. It looks strange to me.

**Comment by NusiNusi** [comment]
I think too that it looks strange when hovering. But it is more the way how it looks. Orange circle over a squircle does not look good IMO. Yes, removing completely would be nice. I am still a fan of this idea for hover:
![orangex](https://user-images.githubusercontent.com/36449926/39345103-dd6de47e-49e6-11e8-8bd8-27b0d9616d86.png)

**Comment by madsrh** [comment]
How about bringing it back?

As I've mentioned earlier, the current design looks a bit neutral/sad/unbranded/...
IMHO I really liked the closebutton + orangesidebar we had before.

**Comment by Feichtmeier** [comment]
+1 for bringing it back
My father also loved the close button as it is a great indicator for where to navigate with the 🐁

**Comment by clobrano** [comment]
I didn't dare to say it, but I'll be very glad to have back both, or at the very least the orange sidebar.

**Comment by NusiNusi** [comment]
**oh god, please no!**

Could we please use real **arguments**?
**The constant orange close-button**:
- a poll showed that users experience an **optical illusion**! This can be a **distraction** from work users are doing with their computer: https://community.ubuntu.com/t/call-for-participation-an-ubuntu-default-theme-lead-by-the-community/1545/835?u=nusi
Is this theme for everyone or for the majority? I am really surprised that this is getting ignored after all.
- even without optical illusion, there is no reason to use a constant-glowing point on the desktop which screams for your attention. nice on screenshots. nice in starbucks. nice for short presentations but a pure distraction when people use the OS for a longer time-period
- the color orange is a pure **attention-grabber** and should be used wisely
- everyone knows where the close-button is, unless he is a new user

The orange background in the sidebar:
- same as close-button: unnecessary attention-grabbing for something that is **already shown by the content itself and by the stackswitcher**. There is just no logic at all to make the sidebar row this showy!
- the orange is too bright to use it as background for white text. Users can experience this as too shiny. Again: Is this theme for everyone or the majority with modern displays and good eyes?
- at the moment the selected sidebar row is the perfect equivalent to the stackswitcher

Please, just no. The theme has a style at the moment:
- gray, dark gray or white backgrounds for white or black text -> **improves** and **guarantees** readability!
- orange is only used in form of lines, rings and borders -> asks for the attention necessary, not more! It is only there where it is needed. This way the use of orange is functional and stylish/elegant at the same time. Orange warning lights and blocks are not functional on an OS which is used for work. **The user wants to focus on the content!**
**At the moment there is no other linux theme which follows its own rules this strict and keeps consistency. This is quality! And not a product of the taste of one designer. I do not think there was ever put so much thought into a theme.**

These are the only arguments i read about going back:
- "IMO it looked better" -> **this is not an argument**
- "I miss it" -> **this is not an argument.**
- Branding! -> Yes, branding is good and important. Does this not look ubuntu-ish enough for you:
![bildschirmfoto von 2018-04-27 14-27-18](https://user-images.githubusercontent.com/36449926/39362562-31f0cd32-4a27-11e8-8e2f-07e535653989.png)

I use Ubuntu since **Ubuntu 7.04 feisty fawn** and never returned to windows. I have no dual-boot. I can tell you ubuntu never looked this modern and usable at the same time.
When it is planned to have this theme as a default we should think about all the people who work with it. Users who only switch some days to ubuntu to play around and reboot to windows really would like a flashy shiny theme.

PLEASE let us use **arguments** and PLEASE let us not go back to the constant glowing light and the orange block. It was **already proven and demonstrated that it is not user-friendly**. At the moment i do not know anymore how to convince you that this would be the wrong way. Really frustrated here.

_We could think about doing a second theme with all this shiny blocks and dots. We could have the communitheme and the communitheme PRO._

**Comment by godlyranchdressing** [comment]
@NusiNusi I'd prefer for the close buttons to all be circles, honestly. I never liked the squircle effect + circle on the close button, it always looked like too much. And of course, my obligatory default argument: in Unity 8 they're all circles and the close button has a red background when hovering on it.

As for the orange bar for the sidebar, I've come to like the little strip but I still think selected rows could do with some more emphasis and the line effect could be similar to the stackswitcher. Right now I have to look for a microsecond to see the orange strip.
![sidebar](https://user-images.githubusercontent.com/27529229/39363110-1d037ed6-49f7-11e8-8c8a-f08fcd0c1622.gif)

**Comment by CDrummond** [comment]
@NusiNusi As always, just my opinion, but... the close button is a destructive action, therefore this should be highlighted in someway. Hence liking the orange (or even red) circle (or background) to indicate that this button is different. Both Windows and macOS have a red background colour for the close button.

**Comment by Feichtmeier** [comment]
Ok here we go, I only speak for the close button though, because this is the topic of this thread, isn't it?

General arguments:
- there are many icons in the header bar, and the modern gtkheaderbar uses _symbolic_ icons for **every** icon and this results in a focus loss if you want to close the window -> where is the close button?
- in non-perfect situations the thin close button becomes hard to see
- the orange close button gives the window a direction -> the top right

Arguments that consider users that used ubuntu and therefor ambiance before communitheme:
- ambiance has an orange close button since? I don't know, you could tell me, since I started to use ubuntu at 14.04 -> recognition value (Wiedererkennungswert)

Refinements if we keep the button:
- I heavily +1 @godlyranchdressing 's argument - this is my main problem with the current state, the mix of a squircle background and a circle button -> I would like to test a circles only window control panel (perma circle close button + hover circle background for min max)

**Comment by godlyranchdressing** [comment]
@Feichtmeier 
![b](https://user-images.githubusercontent.com/27529229/39371102-b5d510e0-4a0e-11e8-969f-6485a8839fd1.gif)
![a](https://user-images.githubusercontent.com/27529229/39371103-b5f34114-4a0e-11e8-9f64-d579395fee24.gif)

**Comment by Ads20000** [comment]
> even without optical illusion, there is no reason to use a constant-glowing point on the desktop which screams for your attention. nice on screenshots. nice in starbucks. nice for short presentations but a pure distraction when people use the OS for a longer time-period
> the color orange is a pure attention-grabber and should be used wisely

@NusiNusi would you argue that the orange pips in the Dock should be scrapped as well then? What about the Firefox logo? And the desktop background?

![screenshot from 2018-04-27 19-35-02](https://user-images.githubusercontent.com/3178485/39379128-40854500-4a52-11e8-97aa-a8cc290c9872.png)

I'm not sure about the 'optical illusion' thingy, maybe that is a thing, maybe not, I don't know.

**Comment by Ads20000** [comment]
> I would like to test a circles only window control panel (perma circle close button + hover circle background for min max)

@Feichtmeier I would like a squircles only window control panel - the orange should either fill the whole squircle (and the close button in Activities should also be an orange squircle) or it should be scrapped entirely. Worth noting that the close tabs button in Firefox, Files and Text Editor are grey squircles so maybe, sad as it is, the window close button should be as well, or it should be orange because it's a more significant close button.

**Comment by Ads20000** [comment]
> Arguments are not an opinion.

I think they can be. It's your analysis of the evidence that there is an optical illusion and its your opinion that avoiding said optical illusion should be a priority.

**Comment by clobrano** [comment]
To me, the theme lost a lot of personality in the last month, I am just happy about the last week, because the trend seems inverted.

> Is this theme for everyone or for the majority? I am really surprised that this is getting ignored after all.

Of course it is for the majority. I would be awesome if something could be for everyone, but, honestly, how could it be? We are working hard to let the majority be as close as possible to everyone, but we cannot please everyone, nobody can.

And still we spent the last month and a half working on a lot on subtle differences, proposing, testing, reverting back and trying again and again and the bug count grown a lot. We are wasting a bit too much time lately.

I don't like to see arguments/opinions pushed other their natural limits only to promote your own ideas. A poll where only 19 people replied does not prove anything. The idea of "only when necessary" is of course an opinion, and yet the most of us tried to come towards other opinions. Not all of us, however, and this actually gets on my nerves sometimes.

> We could think about doing a second theme with all this shiny blocks and dots

Or the other way around, don't you think?

Using bold text and exclamation marks only show frustration, I'd prefer not seeing it here. The last thing I see here wanted by only one person is the removal of the close button circle. Let's try to move together towards something we can share and appreciate.

**Comment by clobrano** [comment]
About close button hover circular, how does it look close to the the other buttons that use squircle?

**Comment by godlyranchdressing** [comment]
@clobrano 

![peek 2018-04-28 11-25](https://user-images.githubusercontent.com/27529229/39398105-dec2772c-4ad6-11e8-8f60-547b63af70f0.gif)

I can open a PR so we can test it live.

**Comment by clobrano** [comment]
Ok, so my idea was to initially test with the orange circle only on hover, what do you think?

**Comment by godlyranchdressing** [comment]
@clobrano if it'll only be visible on hover then I think it'll be better for it to be red. The orange here is only for personality/branding, so unless it's visible _all the time_, then the close button's more like a regular destructive button. Having the orange only when hovering won't have the same effect, so best make it red.

**Comment by Feichtmeier** [comment]
I would like to test it the way its in this gif.

**Comment by clobrano** [comment]
You're right, it's in fact a destructive action, but not styled this way in the css. I'd prefer orange and permanent, to red :)

**Comment by ya-d** [comment]
The circles look a bit small to me but that can only be judged seeing them full screen. I would like to add one thing though:

There is an objective issue with the close button which maybe adds to the negative impression for some users. Because of the aliasing in the diagonal lines of the X it looses weight compared to the straight lines of minimize and close. This makes the close icon appear thinner and makes it vanish in the background (be it grey or orange). Maybe this can be offset visually by making the strokes a little bit thicker. [See screenshot above.](https://github.com/ubuntu/gtk-communitheme/issues/369#issuecomment-385007124)

(The same issue is visible for other icons which aren't exactly horizontal or vertical, like the magnifying glas. I use a high res screen, it's probably even worse on low resolutions.)

**Comment by clobrano** [comment]
@ya-d do you know where are the assets for this button?

**Comment by Feichtmeier** [comment]
You can change the color here: https://github.com/ubuntu/gtk-communitheme/blob/master/Communitheme/gtk-3.0/_common.scss#L4592
The close button is taken from "our" icon theme Suru =)

**Comment by ya-d** [comment]
I guess it's [application-exit-symbolic.svg](https://github.com/ubuntu/suru-icon-theme/blob/master/Suru/scalable/actions/application-exit-symbolic.svg) but I absolutely don't know where it lands in the OS.

**Comment by godlyranchdressing** [comment]
@ya-d That'll need to be changed in the icon pack. I think there's an issue open for it already.

**Comment by NusiNusi** [comment]
@clobrano 

> Using bold text and exclamation marks only show frustration, I'd prefer not seeing it here.

The bold text was used for headlines to structure my text and for arguments that were already told and seemed to be completely ignored. I am repeating myself.

> A poll where only 19 people replied does not prove anything.

This is not right. It proved that some people have this experience with the white text over this orange circle. This issue is not a fabrication from me to get rid from an orange dot as many of you seem to think. As i said in the ubuntu hub this can be ignored by you but that would mean that some users with glasses will see the x moving inside an orange circle. You do not experience it. Others in your team do not experience it but others and i experienced it and i took my time to tell you this so that a different solution can be found.

> To me, the theme lost a lot of personality in the last month

This is your opinion. My opinion is the exact opposite because the theme gained a lot of consistency and avoided being a collection of subjective design-preferences. I am repeating myself once again but the theme is using orange in all places as lines, dots and borders to show something is selected or active. Why can't we follow this rule? If the close-button stays orange it has only a branding-purpose.

> And still we spent the last month and a half working on a lot on subtle differences, proposing, testing, reverting back and trying again and again and the bug count grown a lot. We are wasting a bit too much time lately.

This is not because of me. The "bug counts" are growing because we are clearing consistency-issues. If you look at the recently opened issues you will see they are mostly about tiny refinements. The theme seems already finished.

"only when necessary" can surely interpreted as an opinion. I was using it as a guideline to give the use of colours and forms a purpose and logic. I do not understand why this goes on your nerves. This should make decisions even easier.

I am aware that my proposed ideas are not welcomed here at all and get immediate dislikes. This is done to no other helping hand here. They are not even used as a startingpoint for different ideas (really? the orange circle is the only alternative?) Many suggestions from me were repeated later by other users and suddenly got the attention they deserved. This is one thing that goes on my nerves: I am not the enemy and i am not trying to block the development or push my "opinions" over you. The only opinion i have: The use of colors should be consistent and follow a guideline. Without this red line you will turn in circles because it will be all about "i like this" and "no, i like that". You can later even justify the use of colors if someone asks. But i am pretty sure this will only be taken serious when someone else uses this words.
Someone even felt the urge to remember me that i am not part of the team and i do not have the last word. I know there are some of you who want me to stop "helping" and most only think i want to get rid of the color "orange". Even when i explained multiple times the reason. No problem, i can stop "helping" if you feel this makes developing the theme easier.
One last question for you: Is an orange circle with a thin white x the only option?

**Comment by clobrano** [comment]
Your opinions have been so ignored that we are still here talking about them.

You are considering only people with glasses in this illusion issue, while there might be tons of other possible causes, like display, light in the room, etc.
However, I said that the poll does not prove anything, not that does not prove your point. I simply said that I am not going to use it to prove we can keep or remove the circle. That's it.


> This is not because of me.

Of course not.
The theme is not finished. We are almost at the same point where it's been decided to postpone it to 18.10. Few tests on GTK2, No test on Qt, no defined dark variant (some application uses it, so we are kind of forced to provide it).

> the theme is using orange in all places as lines, dots and borders to show something is selected or active. Why can't we follow this rule?

The theme is doing this now, after the "remove orange" topic. Before that we had orange tiles that where fine to me, but since the majority agreed on remove them, we did.
However, when pushed on some applications it makes the theme bland, neutral and unpersonal. This is my opinion of course.


> "only when necessary" can surely interpreted as an opinion. I was using it as a guideline to give the use of colours and forms a purpose and logic. I do not understand why this goes on your nerves. This should make decisions even easier.

You misunderstood. Below is what I wrote.

> the most of us tried to come towards other opinions. Not all of us, however, and this actually gets on my nerves sometimes.

---

> One last question for you: Is an orange circle with a thin white x the only option?

 This idea comes from Ambiance, to let the user remember from where we came from. Anything that can give the same idea will be discussed, but I don't feel that using a red X will do.

 I don't see you as an enemy at all, but sometimes I feel that for you or we agree or we are wrong.

**Comment by Feichtmeier** [comment]
My god so much drama...
Nusi you know this is bullsh*t, you had some great ideas which we implemented. 
Just some things could not be implemented or could get reverted because other people are not +1
Look, for example me: I would like to do this or that and I propose the idea but when it's clear that there are not so many +1 I forget about it.
Also, there is that PR with the close button which we test now.
You should really calm down now and let's get back to work @.@

**Comment by CDrummond** [comment]
First of all - windows controls look great! - I love the new look.

Once slight niggle, when you mouse over the close button on a background/inactive window the close button's orange circle disappears.

**Comment by mivoligo** [comment]
IMHO the orange close button on every open window is not a very good idea. 
If you have few windows open you see orange dots everywhere.
Also in the activity view you get 2 orange buttons next to each other which looks at least weird:
![zrzut ekranu z 2018-05-04 11-16-15](https://user-images.githubusercontent.com/1629120/39625051-a9e3bdec-4f93-11e8-9994-b8706f696508.png)

**Comment by clobrano** [comment]
@godlyranchdressing I think that it should not be orange on backdrop at least

**Comment by jim3872** [comment]
The x and the square doesn't look central to me with chrome in fullscreen. 
![screenshot from 2018-05-04 16-26-42](https://user-images.githubusercontent.com/36636462/39636537-6f15573c-4fb8-11e8-8600-7fc6642763a8.png). It's ok otherwise. 

With the side bar has it been tried with the orange similar to the radiance theme? I.e orange on 'hover-over' with nautilus but used as is for things like the settings menu. Could this be the best of both worlds?

**Comment by Feichtmeier** [comment]
This is a chrome problem check the other gtk themes. Same issue

**Comment by jim3872** [comment]
Pop OS theme is ok. 

![screenshot from 2018-05-04 16-36-57](https://user-images.githubusercontent.com/36636462/39637037-ccd6f0dc-4fb9-11e8-928a-732580675669.png)

**Comment by Feichtmeier** [comment]
![peek 2018-05-05 12-33](https://user-images.githubusercontent.com/15329494/39662391-10d09912-5061-11e8-9bcb-9d6c4fd76f6a.gif)
@madsrh @clobrano @godlyranchdressing you're okay with this for backdrop and backdrop hover?

**Comment by madsrh** [comment]
@Feichtmeier I think it should become brighter on hover like the other buttons 😉 The opposite might work

**Comment by Feichtmeier** [comment]
![peek 2018-05-05 12-59](https://user-images.githubusercontent.com/15329494/39662582-347b0174-5064-11e8-8d7e-b79764940213.gif)
@madsrh like this?

**Comment by Feichtmeier** [comment]
Btw, this somehow reduces the problem with the "orange buttons everywhere" 
![screenshot from 2018-05-05 13-03-23](https://user-images.githubusercontent.com/15329494/39662617-fcf9aa10-5064-11e8-891c-461d03c4eec1.png)

**Comment by CDrummond** [comment]
(And, just to butt in where I'm not wanted...) If we have hover-effects for window buttons on inactive windows, surely we should have them for all widgets? ie. #194

**Comment by Feichtmeier** [comment]
You are always wanted!
You mean like in ambiance?
![peek 2018-05-05 13-09](https://user-images.githubusercontent.com/15329494/39662660-9cad3e64-5065-11e8-94d0-a6b38ba1cf36.gif)

**Comment by CDrummond** [comment]
(The bit in brackets was in jest). Anyway, most themes (Arc, Ambiance, Pop) react to hover for inactive windows. (Even windows does). But I was referring to all widgets, not just headerbar widgets.

**Comment by Feichtmeier** [comment]
@CDrummond alright. Let's discuss this in the other issue then :) I'll only work on the buttons now - but good idea to bring this up again!

**Comment by madsrh** [comment]
@Feichtmeier Could we try @ubuntujaggers suggestion from [the hub](https://community.ubuntu.com/t/call-for-participation-an-ubuntu-default-theme-lead-by-the-community/1545/1008) ?

Here's a quote:
> Looking at the explanation of the colour use… I would say the odd one out is orange “x”. I actually like it and want to keep it, even though I was initially supportive of removing it (I realised how much I’d missed it when the orange circle came back!). But the use of orange here is pure branding. It doesn’t tie in with the general logic on colours.
As always, just an idea: if you only have the orange “x” for in-focus windows, does that bring it in line with other uses of orange in Communitheme?
Then the explanation is, the orange is being used as another visual indication of focus, current selection, etc… It doubles up as an orange highlight or “pip” on the selected window. That’s consistent with the current thinking around colour and can be justified if people ask why it’s orange (rather than just “it looks good” or “a tribute to the old theme” - explanations that convince me  :slight_smile: but maybe not everyone). And the rationale for having the orange around the “x” would be, it’s a nice/tidy/obvious place to put a small bit of orange to show focus, without it being “too much orange”.
> ![image](https://user-images.githubusercontent.com/3986894/39674996-d77f9204-5154-11e8-9dfb-32e0d6cace5b.png)

**Comment by madsrh** [comment]
I'm closing this issue as it was fixed with https://github.com/ubuntu/gtk-communitheme/commit/0f120b2983c13f137a6cd71d41cb4e5266232ef3

**Comment by Feichtmeier** [comment]
@clobrano I've noticed that though CSD apps work as we designed them together with jaggers on the hub, the pressed/active grey circle disappears on non-CSD apps:

Any idea how this can be changed @clobrano ? :dancing_women: Is there a special class for non-CSD window controls?
![peek 2018-05-08 22-31](https://user-images.githubusercontent.com/15329494/39781473-8e00bd4e-530f-11e8-86c9-dbe1decf558f.gif)

**Comment by Feichtmeier** [comment]
Edit: found it... I've forgotten to include:
  &:backdrop:active{@include draw_circle(darken($headerbar_fg_color,40%), $close:true)}

-.-
