### ISSUE TITLE
Bring back highlight for selected items

### ISSUE THREAD

**Issue by zappedfish** [ubuntu/gtk-communitheme#376]
I hope this would not be a duplicate of another issue...

Some sort of highlight is really needed for two reasons:
- Right now it's hard to spot what exactly is selected (takes a little bit more time to spot that orange stripe)
- If you use keyboard for navigation it becomes very confusing (see screenshot below)

![screenshot from 2018-04-28 18-17-11](https://user-images.githubusercontent.com/36744029/39397455-68a92128-4b10-11e8-806a-d30bf182a0e7.png)

It looks like "Default Applications" item is active, while it's actually "About"

**Comment by Feichtmeier** [comment]
While many agree with you for bringing it back - the bug or wrong behaviour you mentioned does not occur on my installation.

**Comment by Feichtmeier** [comment]
@zappedfish np the general issue comes to the right time =D Because there is some hot discussion going on about bringing it back for other reasons

**Comment by ya-d** [comment]
I can confirm this issue for Files (updated 4-27).
* Files: pressing <tab> moves the selection highlight but content stays where it was. (As seen in first post for Settings.)
* Settings: pressing <tab> does nothing for me. Only search in the top left corner receives the keyboard focus ring. (But it seems to show the same issue as Files in @Feichtmeier's gif.)
* Tweaks: hitting <tab> moves selection highlight _and_ content view -- that's fine.

So this is clearly a bug for Files and Settings. Although it's not entirely caused by Communitheme but upstream Gnome or Apps! (Happens with Adwaita as well.)
(a) <tab> should only move keyboard selection highlight, _not_  active selection highlight (or at least content should move too). => Upstream, should be reported there
(b) the focus ring should be closed on all sides => Communitheme
(c) I wouldn't mind trying @godlyranchdressing's proposal of keeping the grey hover highlight next to the vertical orange line for selection highlight before deciding to go back to plain orange. => Communitheme

**Comment by Feichtmeier** [comment]
Ah thanks for diving into this @ya-d 
So @zappedfish could report this upstream and change the text of the initial post a bit so it fits to a discussion about the sidebar row selection
