### ISSUE TITLE
Appearance

### ISSUE THREAD

**Issue by bianchinirick** [ubuntu/gtk-communitheme#420]
Ugly alt tab after last update - Now it is blank and without transparency.
 The same with the logout/restart/turnoff session buttons.

**Comment by madsrh** [comment]
Hi @bianchinirick 

We're trying out some things with the design. You can read more on the [community hub](https://community.ubuntu.com/t/call-for-participation-an-ubuntu-default-theme-lead-by-the-community/1545/1036) about it.

For future bug reporting, you might want to avoid the word **ugly** as it has a very negative tone 😉 

I'm closing this issue and hope you will participate in the discussion on the hub 👍

**Comment by Feichtmeier** [comment]
Hi there - awesome issue title! :dancer: 

We are currently iterating over several components of the shell and their appearance regarding "light vs dark". You can follow the discussion here on the communityhub (there is even a poll for this topic).

Anyways, closing this now as this is a design experiment and this issue is kind of unproductive :smile:

**Comment by Feichtmeier** [comment]
Wow in the exact same moment... how the hell?

**Comment by madsrh** [comment]
touché ⚔️
