### ISSUE TITLE
Tree expander arows blurry

### ISSUE THREAD

**Issue by CDrummond** [ubuntu/gtk-communitheme#424]
Page 3 of gtk3-widget-factory contains a tree view. The arrows used to expand/collapse a branch seem blurry. This can also be seen in Geary.

**Comment by madsrh** [comment]
![image](https://user-images.githubusercontent.com/3986894/39861478-ff3a92aa-5440-11e8-85eb-a1c924414454.png)

**Comment by clobrano** [comment]
This is probably because we use Adwaita/GNOME's default assets, but in effect on Ambiance triangles look sharper

**Comment by Paz-it** [comment]
@clobrano 
I think the sharp arrow is in the assets as well. when you hover it it turns sharp. it means in the code the link to the sharp arrow is used under the hover section. 
Not sure it's neesed be if you think so you just have to switch the links to the correct image.

**Comment by clobrano** [comment]
Thanks @Paz-it, so this means that it is just a matter of color that makes it blur. I'd take this chance to propose this change instead: recently we changed check and radio button in menus in order to have the same color as their correspondant label. Here the situation is similar, since by default arrows are different than their text. What about this instead?

![treeview-arrow-color](https://user-images.githubusercontent.com/2883614/40938981-af52e5c8-6843-11e8-9509-1deaa06fb342.gif)
