### ISSUE TITLE
Borders in selected wallpaper should be thinner

### ISSUE THREAD

**Issue by clobrano** [Ubuntu/gtk-communitheme#82]
![image](https://user-images.githubusercontent.com/2883614/35183689-6f4cb47c-fdea-11e7-9e3b-763c202cb55e.png)

**Comment by godlyranchdressing** [comment]
A couple of days ago I noticed (by accident) that it's a background color that's being used and not a border. I think it's the usual :selected style being used from %selected_items, but it just looks like a border because of the padding around the image. Selecting an image that's more tall than wide:

![background](https://user-images.githubusercontent.com/27529229/35184776-5c7baf0c-fdd0-11e7-96f4-343a4bc9c73a.png)

**Comment by clobrano** [comment]
Moreover, according to gtkinspector it's a whole object iconview, which does not let you to style the single icons

**Comment by godlyranchdressing** [comment]
Closing since not possible.
